"""画像正文的渲染与新鲜度判定。"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from persona.persona_core import EXTRA_FILE, Ctx, parse_day
from persona.persona_providers import PROVIDERS

HEADER_RE = re.compile(r"built_at=(\d{4}-\d{2}-\d{2})")

def is_stale(path: Path, ttl_days: int) -> tuple[bool, str]:
    if not path.is_file():
        return True, "缓存不存在"
    m = HEADER_RE.search(path.read_text(encoding="utf-8", errors="replace")[:400])
    if not m:
        return True, "缓存头缺少 built_at"
    built = parse_day(m.group(1))
    if built is None:
        return True, "built_at 不可解析"
    age = (date.today() - built).days
    if age > ttl_days:
        return True, f"缓存已 {age} 天 (TTL {ttl_days})"
    return False, f"缓存 {age} 天内有效 (built_at={built})"

def build(ctx: Ctx, ttl: int) -> str:
    secs = [(title, fn(ctx)) for title, fn in PROVIDERS]
    gaps = [f"- **{s.name}**: {s.note or '无数据'}" for _, s in secs if not s.ok]

    out = [
        f"<!-- generated by hx_persona.py  built_at={date.today().isoformat()}  "
        f"ttl={ttl}d  window={ctx.months}m -->",
        "<!-- 不要手改本文件, 下次 build 会覆盖. 手写补充请写 "
        f"{EXTRA_FILE}, 它会被原样并入且优先于自动结论. -->",
        "",
        "# 用户画像",
        "",
        f"窗口: `{ctx.since}` ~ `{date.today()}` (近 {ctx.months} 个月)",
        "",
    ]
    idx = 0
    for title, s in secs:
        if not s.ok:
            continue
        out += [f"## 0x{idx:02X} {title}", ""]
        if s.note:
            out += [f"> {s.note}", ""]
        out += s.lines + [""]
        idx += 1

    out += [f"## 0x{idx:02X} 数据缺口 (这些方向的判断不要硬编)", ""]
    out += (gaps or ["- 无"]) + [""]
    idx += 1

    extra = ctx.root / EXTRA_FILE
    if extra.is_file():
        out += [f"## 0x{idx:02X} 人类补充 (优先于以上全部自动结论)", "",
                extra.read_text(encoding="utf-8").strip(), ""]

    out += [
        "---",
        "",
        "用法约束:",
        "",
        "- 画像用来**选切入点**, 不是用来夸读者. 禁止写成 `你最近在做 X, 而这篇讲 Y`.",
        "- 作者的文章是第一人称自述. 引入段要写成 `我为什么会碰到这个问题`, 不是对读者寒暄.",
        "- 数据缺口里的方向一律不许臆测; 需要时问人类.",
        "",
    ]
    return "\n".join(out)
