// Auto-generated by tag-index-plugin — do not edit manually.
export interface AiDocTagInfo {
  /** 标签原文 (frontmatter 里的写法) */
  label: string;
  /** 与内容插件一致的 slug (lodash.kebabCase) */
  slug: string;
  /** 标签详情页的站内路径 (不含 baseUrl) */
  permalink: string;
  /** 打这个标签的笔记数 */
  count: number;
  /** 注册表 ai-docs/.hx-tags.toml 里的人工描述, 可为空 */
  description: string;
  /** 注册表里声明的直接上级 tag, 顶层为空 */
  parent: string;
  /** 沿 parent 链上溯到的 L1 大类名, 本身就是大类时为空 */
  root: string;
  /** 注册表里登记的同义写法 */
  aliases: string[];
}

export interface AiDocEntry {
  /** 文档 slug (与内容插件保持一致, 目录数字前缀已去掉) */
  id: string;
  title: string;
  description: string;
  /** 站内路径 (不含 baseUrl) */
  permalink: string;
  /** YYYY-MM-DD */
  date: string;
  /** 这篇笔记的标签原文 */
  tags: string[];
}

export interface AiDocTagIndex {
  tags: AiDocTagInfo[];
  docs: AiDocEntry[];
  generatedAt: string;
}

export const aiDocTagIndex: AiDocTagIndex = {
  "tags": [
    {
      "label": "AI Agent",
      "slug": "ai-agent",
      "permalink": "/knowledge-base/tags/ai-agent",
      "count": 15,
      "description": "Agent 系统的设计、架构与工程实践, 不含模型原理本身",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "记忆系统",
      "slug": "记忆系统",
      "permalink": "/knowledge-base/tags/记忆系统",
      "count": 4,
      "description": "长期记忆的存储、召回与演化机制, 不含提示词技巧",
      "parent": "AI Agent",
      "aliases": [
        "可插拔",
        "泛化"
      ],
      "root": "AI Agent"
    },
    {
      "label": "逆向与风控",
      "slug": "逆向与风控",
      "permalink": "/knowledge-base/tags/逆向与风控",
      "count": 4,
      "description": "对抗视角下的浏览器验证、指纹识别与风控机制",
      "parent": "",
      "aliases": [
        "AI逆向"
      ],
      "root": ""
    },
    {
      "label": "Harness",
      "slug": "harness",
      "permalink": "/knowledge-base/tags/harness",
      "count": 4,
      "description": "Agent 运行时/循环/工具调用的实现机制",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Skill",
      "slug": "skill",
      "permalink": "/knowledge-base/tags/skill",
      "count": 4,
      "description": "Agent 技能的编写、打包、训练与评测",
      "parent": "AI Agent",
      "aliases": [
        "项目学习"
      ],
      "root": "AI Agent"
    },
    {
      "label": "多智能体",
      "slug": "多智能体",
      "permalink": "/knowledge-base/tags/多智能体",
      "count": 3,
      "description": "多个 Agent 之间的协作与编排",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "工程实践",
      "slug": "工程实践",
      "permalink": "/knowledge-base/tags/工程实践",
      "count": 3,
      "description": "可直接复用的工程做法与取舍",
      "parent": "AI Agent",
      "aliases": [
        "接口设计"
      ],
      "root": "AI Agent"
    },
    {
      "label": "技术选型",
      "slug": "技术选型",
      "permalink": "/knowledge-base/tags/技术选型",
      "count": 3,
      "description": "在多个方案之间做选择",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "提示词工程",
      "slug": "提示词工程",
      "permalink": "/knowledge-base/tags/提示词工程",
      "count": 3,
      "description": "提示词的设计、优化与预设",
      "parent": "AI Agent",
      "aliases": [
        "提示词优化",
        "预设"
      ],
      "root": "AI Agent"
    },
    {
      "label": "知识库",
      "slug": "知识库",
      "permalink": "/knowledge-base/tags/知识库",
      "count": 3,
      "description": "知识库的组织与存取",
      "parent": "记忆系统",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "DSH",
      "slug": "dsh",
      "permalink": "/knowledge-base/tags/dsh",
      "count": 3,
      "description": "DeepSeek Harness 的具体实现",
      "parent": "Harness",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Turnstile",
      "slug": "turnstile",
      "permalink": "/knowledge-base/tags/turnstile",
      "count": 3,
      "description": "Cloudflare Turnstile 的攻防两侧",
      "parent": "逆向与风控",
      "aliases": [
        "Turnstile防御"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "检测面建模",
      "slug": "检测面建模",
      "permalink": "/knowledge-base/tags/检测面建模",
      "count": 2,
      "description": "攻击者与防御者视角的信号建模",
      "parent": "逆向与风控",
      "aliases": [
        "事件可信度",
        "风控"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "评测",
      "slug": "评测",
      "permalink": "/knowledge-base/tags/评测",
      "count": 2,
      "description": "能力与效果的量化评估",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "上下文工程",
      "slug": "上下文工程",
      "permalink": "/knowledge-base/tags/上下文工程",
      "count": 2,
      "description": "上下文窗口的构造、压缩与组织",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Agent架构",
      "slug": "agent架构",
      "permalink": "/knowledge-base/tags/agent架构",
      "count": 2,
      "description": "Agent 系统的分层与模块解耦设计",
      "parent": "AI Agent",
      "aliases": [
        "Agent平台",
        "基础设施"
      ],
      "root": "AI Agent"
    },
    {
      "label": "AI工具",
      "slug": "ai工具",
      "permalink": "/knowledge-base/tags/ai工具",
      "count": 2,
      "description": "AI 辅助开发的工具链",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "C++",
      "slug": "c",
      "permalink": "/knowledge-base/tags/c",
      "count": 2,
      "description": "C++ 语言、范式与标准演进",
      "parent": "编程语言",
      "aliases": [
        "现代C++",
        "C++20"
      ],
      "root": "编程语言"
    },
    {
      "label": "Codex",
      "slug": "codex",
      "permalink": "/knowledge-base/tags/codex",
      "count": 2,
      "description": "OpenAI Codex CLI 的使用与观察",
      "parent": "Harness",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "MCP",
      "slug": "mcp",
      "permalink": "/knowledge-base/tags/mcp",
      "count": 2,
      "description": "Model Context Protocol 与其生态",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "Multica",
      "slug": "multica",
      "permalink": "/knowledge-base/tags/multica",
      "count": 2,
      "description": "Multica 多智能体协作平台",
      "parent": "多智能体",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Python",
      "slug": "python",
      "permalink": "/knowledge-base/tags/python",
      "count": 2,
      "description": "Python 语言与生态",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "编译期多态",
      "slug": "编译期多态",
      "permalink": "/knowledge-base/tags/编译期多态",
      "count": 1,
      "description": "模板元编程与编译期计算",
      "parent": "C++",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "电脑包",
      "slug": "电脑包",
      "permalink": "/knowledge-base/tags/电脑包",
      "count": 1,
      "description": "电脑包的容量与结构",
      "parent": "选购指标",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "短视频",
      "slug": "短视频",
      "permalink": "/knowledge-base/tags/短视频",
      "count": 1,
      "description": "短视频的内容形态与影响",
      "parent": "生活杂谈",
      "aliases": [
        "想法探索"
      ],
      "root": "生活杂谈"
    },
    {
      "label": "检索",
      "slug": "检索",
      "permalink": "/knowledge-base/tags/检索",
      "count": 1,
      "description": "Agent 的外部检索与 RAG 链路",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "可复现性",
      "slug": "可复现性",
      "permalink": "/knowledge-base/tags/可复现性",
      "count": 1,
      "description": "结果可被稳定复现",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "浏览器指纹",
      "slug": "浏览器指纹",
      "permalink": "/knowledge-base/tags/浏览器指纹",
      "count": 1,
      "description": "浏览器与 TLS 指纹的构成和识别",
      "parent": "逆向与风控",
      "aliases": [
        "TLS指纹"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "浏览器自动化",
      "slug": "浏览器自动化",
      "permalink": "/knowledge-base/tags/浏览器自动化",
      "count": 1,
      "description": "Playwright 等浏览器自动化手段",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "毛选方法论",
      "slug": "毛选方法论",
      "permalink": "/knowledge-base/tags/毛选方法论",
      "count": 1,
      "description": "用毛选的方法分析现实问题",
      "parent": "生活杂谈",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "逆向工程",
      "slug": "逆向工程",
      "permalink": "/knowledge-base/tags/逆向工程",
      "count": 1,
      "description": "逆向分析的方法与经验",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "爬虫",
      "slug": "爬虫",
      "permalink": "/knowledge-base/tags/爬虫",
      "count": 1,
      "description": "网络数据采集与解析",
      "parent": "Python",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "凭证管理",
      "slug": "凭证管理",
      "permalink": "/knowledge-base/tags/凭证管理",
      "count": 1,
      "description": "密钥与凭据的存放和轮换",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "前端",
      "slug": "前端",
      "permalink": "/knowledge-base/tags/前端",
      "count": 1,
      "description": "Web 前端框架与交互实现",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "前端动画",
      "slug": "前端动画",
      "permalink": "/knowledge-base/tags/前端动画",
      "count": 1,
      "description": "交互动效与动画实现",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "数据面",
      "slug": "数据面",
      "permalink": "/knowledge-base/tags/数据面",
      "count": 1,
      "description": "数据面与控制面的职责切分",
      "parent": "Agent架构",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "通勤",
      "slug": "通勤",
      "permalink": "/knowledge-base/tags/通勤",
      "count": 1,
      "description": "通勤场景下的取舍",
      "parent": "选购指标",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "协程",
      "slug": "协程",
      "permalink": "/knowledge-base/tags/协程",
      "count": 1,
      "description": "协程模型与异步调度",
      "parent": "C++",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "选购指标",
      "slug": "选购指标",
      "permalink": "/knowledge-base/tags/选购指标",
      "count": 1,
      "description": "买东西时真正该看的指标",
      "parent": "生活杂谈",
      "aliases": [
        "商品选购"
      ],
      "root": "生活杂谈"
    },
    {
      "label": "验证码求解",
      "slug": "验证码求解",
      "permalink": "/knowledge-base/tags/验证码求解",
      "count": 1,
      "description": "验证码识别与自动化求解",
      "parent": "逆向与风控",
      "aliases": [
        "AI验证码求解"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "异步任务",
      "slug": "异步任务",
      "permalink": "/knowledge-base/tags/异步任务",
      "count": 1,
      "description": "异步任务的组织与调度",
      "parent": "协程",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "语言特性",
      "slug": "语言特性",
      "permalink": "/knowledge-base/tags/语言特性",
      "count": 1,
      "description": "语言层面的特性与设计取舍",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "约束解码",
      "slug": "约束解码",
      "permalink": "/knowledge-base/tags/约束解码",
      "count": 1,
      "description": "用语法/结构约束模型输出格式",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "增量沉淀",
      "slug": "增量沉淀",
      "permalink": "/knowledge-base/tags/增量沉淀",
      "count": 1,
      "description": "只追加不重写的沉淀方式",
      "parent": "记忆系统",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "注意力",
      "slug": "注意力",
      "permalink": "/knowledge-base/tags/注意力",
      "count": 1,
      "description": "注意力被如何捕获与消耗",
      "parent": "生活杂谈",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "自建部署",
      "slug": "自建部署",
      "permalink": "/knowledge-base/tags/自建部署",
      "count": 1,
      "description": "自托管服务与网络配置",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "组件库",
      "slug": "组件库",
      "permalink": "/knowledge-base/tags/组件库",
      "count": 1,
      "description": "可复用 UI 组件与其设计",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "Bot Defense",
      "slug": "bot-defense",
      "permalink": "/knowledge-base/tags/bot-defense",
      "count": 1,
      "description": "产品侧的反爬与人机策略",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "KV Cache",
      "slug": "kv-cache",
      "permalink": "/knowledge-base/tags/kv-cache",
      "count": 1,
      "description": "注意力键值缓存与推理优化",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "LLM",
      "slug": "llm",
      "permalink": "/knowledge-base/tags/llm",
      "count": 1,
      "description": "大语言模型的能力边界与基本原理",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "OAuth",
      "slug": "o-auth",
      "permalink": "/knowledge-base/tags/o-auth",
      "count": 1,
      "description": "OAuth 授权流程与令牌",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "react",
      "slug": "react",
      "permalink": "/knowledge-base/tags/react",
      "count": 1,
      "description": "React 及其生态组件",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "Tokenization",
      "slug": "tokenization",
      "permalink": "/knowledge-base/tags/tokenization",
      "count": 1,
      "description": "分词与 token 化对模型行为的影响",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "编程语言",
      "slug": "编程语言",
      "permalink": "/knowledge-base/tags/编程语言",
      "count": 0,
      "description": "语言本身的特性、范式与技术选型",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "工程与工具",
      "slug": "工程与工具",
      "permalink": "/knowledge-base/tags/工程与工具",
      "count": 0,
      "description": "开发工具链、部署、协作与可复现性",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "生活杂谈",
      "slug": "生活杂谈",
      "permalink": "/knowledge-base/tags/生活杂谈",
      "count": 0,
      "description": "个人生活、选购与读书杂谈",
      "parent": "",
      "aliases": [],
      "root": ""
    }
  ],
  "docs": [
    {
      "id": "AI/记忆/Agent-Memory框架选型",
      "title": "Agent Memory 选型指南: 五大范式、评测水分与四个必补动作",
      "description": "NOTE 同一个记忆框架, 在自家 benchmark 上可以报到 94.4 分 —— 而这个数字来自厂商托管平台的自测. 更麻烦的是: 同一类系统换一套测试脚手架, 分数能相差几十个百分点, 变量既不是模型也不是产品, 而是 谁写的评测代码 . 那么问题就不是\"该买哪个\", 而是: 在一个连分数都不可比的领域里, 选",
      "permalink": "/knowledge-base/AI/记忆/Agent-Memory框架选型",
      "date": "2026-09-13",
      "tags": [
        "AI Agent",
        "记忆系统",
        "技术选型",
        "评测"
      ]
    },
    {
      "id": "AI/记忆/obsidian-second-brain",
      "title": "obsidian-second-brain 全解: 一个会自我重写的 AI 知识库",
      "description": "NOTE 你的笔记库在半年后会比今天更聪明吗? 大多数\"第二大脑\"的答案是不会 —— 它们只是一个更整齐的文件柜: 放进去的东西原样躺着, 三个月前的决策和昨天的决策互相矛盾, 而没有任何人知道. obsidian second brain 想换掉这个前提: 知识库不是往里面加东西, 而是围绕新信息重写自己 . 那么,",
      "permalink": "/knowledge-base/AI/记忆/obsidian-second-brain",
      "date": "2026-09-13",
      "tags": [
        "记忆系统",
        "知识库",
        "Skill",
        "AI Agent"
      ]
    },
    {
      "id": "AI/检索/自建Agent检索栈与凭证治理",
      "title": "自建 Agent 检索栈: 本地化边界、凭证治理与可用性证明",
      "description": "0x00 背景 给 Agent 接检索, 很多人默认的做法是\"买一个搜索 API 然后填 key\". 但一旦把约束换成下面两条, 整个方案形态就变了: 1. 尽量完全本地自建 — 检索链路不依赖商业检索 API, 数据不出本机, 成本可预测, 不受第三方限流与条款变动摆布. 2. 凭证配置必须体面 — 社交平台终究要 ",
      "permalink": "/knowledge-base/AI/检索/自建Agent检索栈与凭证治理",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "检索",
        "MCP",
        "自建部署",
        "OAuth",
        "凭证管理"
      ]
    },
    {
      "id": "AI/Skill/Agent-Skill编写最佳实践",
      "title": "Agent Skill 编写最佳实践: 上下文预算、触发工程与可证伪的验证",
      "description": "0x00 背景 大多数人写 skill 的方式是这样的: 把知道的都写进去, 写长了就删一点, 看起来完整就交差. 于是最常见的结果是两种 —— 要么这个 skill 永远不会被触发, 要么它把上下文窗口占满而收益极低 . 这两种失败有一个共同的、隐蔽的特征: 它们都不会报错 . 名字写错、触发条件写在正文里、正文长到",
      "permalink": "/knowledge-base/AI/Skill/Agent-Skill编写最佳实践",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "上下文工程",
        "提示词工程",
        "工程实践"
      ]
    },
    {
      "id": "AI/Skill/SkillOpt把skill当参数训练",
      "title": "SkillOpt: 把 skill 文档当参数来训练, 以及它在规范与可复现性上的边界",
      "description": "0x00 背景 给 agent 加能力, 主流做法是写一份 skill —— 一个目录, 里面有 SKILL.md 和可选的脚本与参考文件. 但写好一份 skill 很难, 于是出现了一类很自然的想法: 既然改提示词有效, 那能不能像训练神经网络一样\"训练\"这份 markdown? SkillOpt 是这类想法里工程化",
      "permalink": "/knowledge-base/AI/Skill/SkillOpt把skill当参数训练",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "提示词工程",
        "可复现性",
        "评测"
      ]
    },
    {
      "id": "AI/记忆/自维护可插拔记忆层设计",
      "title": "自维护可插拔记忆层设计: 一次对比市面方案后的收敛",
      "description": "0x00 背景 要给 HXLoLi 的 AI 生态 DSH 为主, 未来可能还有 Codex/其他 CLI 配一套长期记忆层. 两个硬需求: 1. 所有 AI 都能读我的知识库 从任何工作区, 只要我允许 ; 2. 知识是关联/渐进/可推广的 —— 不只是 top k 相似度, 而是能从一个具体事故 例如\"后端队列并发",
      "permalink": "/knowledge-base/AI/记忆/自维护可插拔记忆层设计",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH预设提示词全解",
      "title": "DeepSeek Harness 提示词全解: 四个预设与每一步投递",
      "description": "DeepSeek Harness 不是一个聊天机器人, 而是一台把\"提示词\"当作可插拔资产来组装的运行时. 本文逐字抄录这台运行时在每一步 实际投递给模型 的提示词: 系统提示词由哪些段 section 按什么顺序拼成, 每次用户消息后追加的运行时上下文快照长什么样, 每个工具的引导文本与描述原文, 以及 plan /",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH预设提示词全解",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH",
        "提示词工程"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH-Agent-Loop源码剖析",
      "title": "DSH Agent Loop 源码剖析",
      "description": "直接读 DeepSeek Harness 源码 packages/core/agent loop, 版本 0.1.x, monorepo: github.com/deepseek ai/dsh , 把 ReactLoopAgent 的驱动循环、事件日志、工具回灌与上下文压缩讲清楚. 图中每个节点都是真实代码里的方法名/",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH-Agent-Loop源码剖析",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH-Runtime设计思想插件树与事件日志",
      "title": "DeepSeek Harness设计思想: 插件树与事件日志",
      "description": "0x00 这篇文章要回答什么? 几十行代码就能写一个能跑的 agent: 收一条用户消息, 拼好提示词请求模型, 模型要调用工具就执行工具, 再把结果放回上下文. 可一旦这个 agent 要 连续工作、修改真实文件、崩溃之后接着完成 , 问题就不再是\"调用模型\"了: 模型调用到一半进程崩了怎么办? 工具已经改了文件, ",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH-Runtime设计思想插件树与事件日志",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH"
      ]
    },
    {
      "id": "杂谈/短视频-精神鸦片",
      "title": "短视频=精神鸦片: 用毛选方法论解构注意力成瘾",
      "description": "NOTE 本文提炼自 B 站视频《毛选实战局》一期节目 BV1Xv8x6uEqa , 拆解短视频成瘾的机制, 并借用毛选的方法论给出应对思路. 适合正在和短视频反复拉扯、想找回专注力的人阅读. 0x00 背景 你是否有过这样的经历: 反复卸载短视频 App, 又反复装回来; 越想早点睡, 越是刷到凌晨三点; 遇到一点困",
      "permalink": "/knowledge-base/杂谈/短视频-精神鸦片",
      "date": "2026-09-04",
      "tags": [
        "短视频",
        "注意力",
        "毛选方法论"
      ]
    },
    {
      "id": "AI/记忆/对话记忆与知识库增量沉淀",
      "title": "AI Agent 对话记忆与知识库增量沉淀设计",
      "description": "NOTE 0x00 背景 要解决的问题 : 一个 Agent 如 AI 助手 / coding copilot 与用户长期交互, 会产生海量对话日志. 日志本身不是知识. 我们真正想要的, 是把日志里 对当前决策/复用有长期价值的信息 , 增量地固化成一个\"项目知识库\", 并且: 1. 实时处于最新状态 —— 知识库要",
      "permalink": "/knowledge-base/AI/记忆/对话记忆与知识库增量沉淀",
      "date": "2026-08-31",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库",
        "增量沉淀"
      ]
    },
    {
      "id": "程序语言/Python/Python语言核心特性调研",
      "title": "Python 语言核心特性调研",
      "description": "NOTE 0x00 一句话总结 Python is an easy to learn, powerful programming language. It has efficient high level data structures and a simple but effective approach to 0x",
      "permalink": "/knowledge-base/程序语言/Python/Python语言核心特性调研",
      "date": "2026-08-30",
      "tags": [
        "Python",
        "语言特性",
        "技术选型"
      ]
    },
    {
      "id": "AI/AI逆向/多模态AI通用验证码求解服务",
      "title": "用AI从零实现通用验证码求解服务:OhMyCaptcha原理剖析",
      "description": "NOTE 当\"看懂图片\"这件事从传统 CV 的模板匹配/图像处理, 变成\"直接问多模态大模型\", 验证码求解的架构会简化多少? 代价又是什么? 0x00 背景 本笔记沉淀 nax 的博客 文章《用 AI 从零实现通用验证码求解服务: OhMyCaptcha 原理剖析》 2026 06 02 . 原文剖析开源项目 OhM",
      "permalink": "/knowledge-base/AI/AI逆向/多模态AI通用验证码求解服务",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "验证码求解",
        "浏览器自动化"
      ]
    },
    {
      "id": "AI/AI逆向/真实浏览器扩展的验证机制拆解",
      "title": "Infinitoai与Turnstile:一次浏览器验证机制的技术拆解",
      "description": "NOTE 一个\"会点复选框\"的脚本和一个\"看起来像真人\"的脚本, 差距究竟在哪一层? 是注入时机, 是事件来源, 还是页面状态感知? 0x00 背景 本笔记沉淀 nax 的博客 文章《Infinitoai 与 Turnstile: 一次浏览器验证机制的技术拆解》 2026 04 18 . 原文以开源项目 Infinit",
      "permalink": "/knowledge-base/AI/AI逆向/真实浏览器扩展的验证机制拆解",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "检测面建模"
      ]
    },
    {
      "id": "AI/AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "title": "深入理解Cloudflare过盾原理:无需AI从零实现CFTurnstile绕过",
      "description": "NOTE 当一个系统反复向你证明\"你是机器人\"时, 它到底在看什么? 是屏幕上的图片, 还是你浏览器内核里每一个不自洽的细节? 0x00 背景 Turnstile 与传统验证码有一个根本差异: 它几乎不出视觉题. 没有扭曲字母, 也没有九宫格选图, 只是在后台收集你浏览器的环境信号, 再判断\"这个环境是不是一个真实的人",
      "permalink": "/knowledge-base/AI/AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "浏览器指纹"
      ]
    },
    {
      "id": "AI/AI逆向/Turnstile防御面分析与误判权衡",
      "title": "CloudflareTurnstile防御分析:浏览器信号检测面与误判权衡",
      "description": "NOTE 如果一个验证组件注定无法 100% 拦截自动化, 那它存在的意义是什么? 是\"绝对正确\", 还是\"把攻击成本抬到不值得\"? 0x00 背景 本笔记沉淀 nax 的博客 文章《Cloudflare Turnstile 防御分析: 浏览器信号、检测面与误判权衡》 2026 06 03 . 原文站在防御者视角, 分",
      "permalink": "/knowledge-base/AI/AI逆向/Turnstile防御面分析与误判权衡",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "检测面建模",
        "Bot Defense"
      ]
    },
    {
      "id": "AI/基础/Agent要懂的LLM基础知识",
      "title": "Agent要懂的LLM基础知识",
      "description": "NOTE 0x00 一句话总结 Agent 的本质是反复调用 LLM 的循环. 循环里的\"玄学问题\"——聊到 20 30 轮突然不守规矩、第 101 次工具调用输出坏 JSON——不是框架 bug, 而是 LLM 的性质. 从 输入 分词 → 上下文 怎么读 → 输出 怎么采样 → 成本延迟 → 能力边界 五个角度都能",
      "permalink": "/knowledge-base/AI/基础/Agent要懂的LLM基础知识",
      "date": "2026-08-10",
      "tags": [
        "AI Agent",
        "LLM",
        "Tokenization",
        "KV Cache",
        "约束解码"
      ]
    },
    {
      "id": "AI/Agent架构/AI-Agent设计原理与工程实践",
      "title": "AI Agent设计原理与工程实践",
      "description": "NOTE 0x00 一句话总结 生产可用的 Agent 不是\"模型很强\", 而是 Agent = LLM + 上下文 + 工具 + 约束 + 验证 + 纠正 : 模型能力差距在收窄, 竞争优势转移到模型之外的 harness 外壳/脚手架 上. 全书 10 章围绕上下文工程、记忆、工具防护、代码、评估、数据、持续优化、",
      "permalink": "/knowledge-base/AI/Agent架构/AI-Agent设计原理与工程实践",
      "date": "2026-08-10",
      "tags": [
        "AI Agent",
        "Agent架构",
        "上下文工程",
        "多智能体",
        "工程实践"
      ]
    },
    {
      "id": "工具链/从打野到注册机与AI工具链",
      "title": "从打野到注册机：一条真实项目工具链的工程化学习",
      "description": "NOTE 0x00 背景 本文沉淀 Discord 论坛帖子《个人常用项目推荐 打野到注册机一条龙, 简易教程 》. 帖子发表于 2026 07 01, 作者为 𝑏𝑎𝑖𝑞𝑖_𝑞𝑎𝑞 , 所在服务器为 KYL , 论坛频道为 🌐 各类教程 chatgpt🚀 . 原帖的主题不是“推荐几个 GitHub ",
      "permalink": "/knowledge-base/工具链/从打野到注册机与AI工具链",
      "date": "2026-08-02",
      "tags": [
        "AI工具",
        "逆向工程",
        "Codex",
        "MCP"
      ]
    },
    {
      "id": "AI/Agent架构/Agent平台数据面灵活解耦",
      "title": "Agent平台数据面灵活解耦",
      "description": "NOTE 0x00 背景 Agent 平台通常由控制面和数据面组成. 控制面面向用户, 管理 workspace 的元数据与配置; 数据面承载 Agent 的实际运行环境, 包括文件系统、命令执行和工具调用. 随着 workspace 数量增加、运行环境分化以及企业网络隔离需求出现, 单一数据面会逐渐成为扩展和安全上的",
      "permalink": "/knowledge-base/AI/Agent架构/Agent平台数据面灵活解耦",
      "date": "2026-07-15",
      "tags": [
        "AI Agent",
        "Agent架构",
        "数据面"
      ]
    },
    {
      "id": "工具链/RTK项目使用说明与Codex本地心得",
      "title": "RTK项目使用说明与Codex本地心得",
      "description": "NOTE 0x00 背景 本文沉淀的是 rtk ai/rtk 项目, 即 RTK / Rust Token Killer . 它不是 Redux Toolkit, 也不是别的同名 Rust Type Kit. 这个项目的核心定位是: 在 AI 编程助手执行 shell 命令时, 先把命令输出过滤、压缩、分组、截断或去重",
      "permalink": "/knowledge-base/工具链/RTK项目使用说明与Codex本地心得",
      "date": "2026-07-05",
      "tags": [
        "AI工具",
        "Codex",
        "Harness"
      ]
    },
    {
      "id": "生活/电脑包选购指标",
      "title": "电脑包选购指标",
      "description": "NOTE 这篇笔记来自一段电脑包选购视频的转写整理, 已按「不讨论具体品牌/型号, 只沉淀可复用指标」处理. 0x00 背景 电脑包很容易被商品标题误导: 「大容量」「商务」「旅行」「多功能」「轻便」这些词看起来都对, 但实际到手后可能容量虚、电脑塞不下、背着勒肩、功能多但太重. 所以选电脑包时真正需要先问的不是「哪款",
      "permalink": "/knowledge-base/生活/电脑包选购指标",
      "date": "2026-07-05",
      "tags": [
        "选购指标",
        "电脑包",
        "通勤"
      ]
    },
    {
      "id": "AI/多智能体/Multica-agent协作与上下文机制",
      "title": "Multica agent协作与上下文机制",
      "description": "NOTE 这是一篇来自 Multica issue 讨论的阶段性沉淀, 不是 Multica 官方文档. 结论以当前 workspace 运行时注入信息、 multica CLI 读到的 issue/comment 内容和 agent 实际约束为依据. 0x00 背景 这次讨论从一个实践问题开始: 在 Multica ",
      "permalink": "/knowledge-base/AI/多智能体/Multica-agent协作与上下文机制",
      "date": "2026-07-05",
      "tags": [
        "多智能体",
        "Multica",
        "AI Agent"
      ]
    },
    {
      "id": "AI/多智能体/Multica智能体模板与小队编排skills调研",
      "title": "Multica智能体模板与小队编排skills调研",
      "description": "NOTE 0x00 背景 这次调研的直接目标是: 为 Multica 工作区设计一组可复用的 skill, 用来创建智能体、选择和绑定能力、组建小队、编排 issue/stage/autopilot, 并让这些能力真正做到可定制、可快速集成、持续可靠可维护. 现有参考是 /home/hx/Loli/code/HXLoL",
      "permalink": "/knowledge-base/AI/多智能体/Multica智能体模板与小队编排skills调研",
      "date": "2026-07-05",
      "tags": [
        "多智能体",
        "Multica",
        "Skill",
        "AI Agent"
      ]
    },
    {
      "id": "程序语言/现代C++/现代C++编译期多态审视",
      "title": "现代C++编译期多态审视",
      "description": "NOTE 0x00 这篇视频真正要回答什么? 视频讨论的不是一句粗暴的「以后别写 virtual 」, 而是一个更有工程价值的问题: 当程序的类型集合、接口约束和调度路径能够在编译期表达时, 是否还需要把多态性推迟到运行期? 来源信息: 视频: C++虚函数可以彻底抛弃了? 现代C++编译期多态实战 CppCon UP",
      "permalink": "/knowledge-base/程序语言/现代C++/现代C++编译期多态审视",
      "date": "2026-07-04",
      "tags": [
        "C++",
        "编译期多态",
        "工程实践"
      ]
    },
    {
      "id": "程序语言/Python/Python爬虫库选型调研",
      "title": "Python爬虫库选型调研",
      "description": "NOTE 当准备写一个 Python 爬虫时, 真正需要先回答的问题不是「哪个库最强」, 而是: 目标页面是否静态? 是否需要登录和浏览器交互? 采集规模是否需要调度、重试和持久化? 最终要的是结构化字段, 还是网页正文? 0x00 背景 Python 爬虫生态里常见库很多, 但它们并不在同一个层级竞争: reques",
      "permalink": "/knowledge-base/程序语言/Python/Python爬虫库选型调研",
      "date": "2026-07-04",
      "tags": [
        "Python",
        "爬虫",
        "技术选型"
      ]
    },
    {
      "id": "程序语言/Web前端/react-bits分门别类学习",
      "title": "react-bits 分门别类学习",
      "description": "NOTE PPT ppt 0x00 背景 react bits 是一个面向 React 的动效组件源码库, 不是传统意义上 npm install 后直接 import 的运行时组件库. 它的核心价值是把一批视觉表达强、可复制、可按技术栈选择的组件组织成注册表, 再通过文档站、预览、代码面板、shadcn/jsrepo",
      "permalink": "/knowledge-base/程序语言/Web前端/react-bits分门别类学习",
      "date": "2026-07-04",
      "tags": [
        "react",
        "前端",
        "前端动画",
        "组件库"
      ]
    },
    {
      "id": "程序语言/现代C++/HXLibs编写串行协程调度器",
      "title": "HXLibs 协程串行调度器探索",
      "description": "记录 SerialExecutor 三轮迭代的探索过程与踩坑经验. 当前版本仍非最终方案, 调度策略尚有优化空间. 相关提交: 50c931c — feat 实现了串行调度器 生命周期敏感 ac74126 — fix 修复 constexpr 编译报错 测试用例 0x00 调度点: 核心思想 在 C++20 无栈协程中",
      "permalink": "/knowledge-base/程序语言/现代C++/HXLibs编写串行协程调度器",
      "date": "2026-06-04",
      "tags": [
        "C++",
        "协程",
        "异步任务"
      ]
    },
    {
      "id": "关于",
      "title": "关于",
      "description": "TIP 这里是 HXLoLi 的 AI 沉淀知识库. 当作者懒得写笔记的时候. 则会在此处沉淀. 以防止污染笔记. 此处的笔记应该是使用 skill 按照一定规范和工作流生成. 需要用户 review 修改后再提交. 目标: 减少编写笔记的时间 非期望: 使用ai瞎jb产出",
      "permalink": "/knowledge-base/关于",
      "date": "2026-06-04",
      "tags": []
    }
  ],
  "generatedAt": "2026-09-13T14:48:56.777Z"
};
