// Auto-generated by tag-index-plugin — do not edit manually.
export interface AiDocTagInfo {
  /** 标签原文 (frontmatter 里的写法) */
  label: string;
  /** 与内容插件一致的 slug (lodash.kebabCase) */
  slug: string;
  /** 标签详情页的站内路径 (不含 baseUrl) */
  permalink: string;
  /** 打这个标签的笔记数 */
  count: number;
  /** 注册表 ai-docs/.hx-tags.toml 里的人工描述, 可为空 */
  description: string;
  /** 注册表里声明的直接上级 tag, 顶层为空 */
  parent: string;
  /** 沿 parent 链上溯到的 L1 大类名, 本身就是大类时为空 */
  root: string;
  /** 注册表里登记的同义写法 */
  aliases: string[];
}

export interface AiDocEntry {
  /** 文档 slug (与内容插件保持一致, 目录数字前缀已去掉) */
  id: string;
  title: string;
  description: string;
  /** 站内路径 (不含 baseUrl) */
  permalink: string;
  /** YYYY-MM-DD */
  date: string;
  /** 这篇笔记的标签原文 */
  tags: string[];
}

export interface AiDocTagIndex {
  tags: AiDocTagInfo[];
  docs: AiDocEntry[];
  generatedAt: string;
}

export const aiDocTagIndex: AiDocTagIndex = {
  "tags": [
    {
      "label": "AI Agent",
      "slug": "ai-agent",
      "permalink": "/knowledge-base/tags/ai-agent",
      "count": 15,
      "description": "Agent 系统的设计、架构与工程实践, 不含模型原理本身",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "记忆系统",
      "slug": "记忆系统",
      "permalink": "/knowledge-base/tags/记忆系统",
      "count": 4,
      "description": "长期记忆的存储、召回与演化机制, 不含提示词技巧",
      "parent": "AI Agent",
      "aliases": [
        "可插拔",
        "泛化"
      ],
      "root": "AI Agent"
    },
    {
      "label": "逆向与风控",
      "slug": "逆向与风控",
      "permalink": "/knowledge-base/tags/逆向与风控",
      "count": 4,
      "description": "对抗视角下的浏览器验证、指纹识别与风控机制",
      "parent": "",
      "aliases": [
        "AI逆向"
      ],
      "root": ""
    },
    {
      "label": "Harness",
      "slug": "harness",
      "permalink": "/knowledge-base/tags/harness",
      "count": 4,
      "description": "Agent 运行时/循环/工具调用的实现机制",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Skill",
      "slug": "skill",
      "permalink": "/knowledge-base/tags/skill",
      "count": 4,
      "description": "Agent 技能的编写、打包、训练与评测",
      "parent": "AI Agent",
      "aliases": [
        "项目学习"
      ],
      "root": "AI Agent"
    },
    {
      "label": "多智能体",
      "slug": "多智能体",
      "permalink": "/knowledge-base/tags/多智能体",
      "count": 3,
      "description": "多个 Agent 之间的协作与编排",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "工程实践",
      "slug": "工程实践",
      "permalink": "/knowledge-base/tags/工程实践",
      "count": 3,
      "description": "可直接复用的工程做法与取舍",
      "parent": "AI Agent",
      "aliases": [
        "接口设计"
      ],
      "root": "AI Agent"
    },
    {
      "label": "技术选型",
      "slug": "技术选型",
      "permalink": "/knowledge-base/tags/技术选型",
      "count": 3,
      "description": "在多个方案之间做选择",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "提示词工程",
      "slug": "提示词工程",
      "permalink": "/knowledge-base/tags/提示词工程",
      "count": 3,
      "description": "提示词的设计、优化与预设",
      "parent": "AI Agent",
      "aliases": [
        "提示词优化",
        "预设"
      ],
      "root": "AI Agent"
    },
    {
      "label": "知识库",
      "slug": "知识库",
      "permalink": "/knowledge-base/tags/知识库",
      "count": 3,
      "description": "知识库的组织与存取",
      "parent": "记忆系统",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "DSH",
      "slug": "dsh",
      "permalink": "/knowledge-base/tags/dsh",
      "count": 3,
      "description": "DeepSeek Harness 的具体实现",
      "parent": "Harness",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Turnstile",
      "slug": "turnstile",
      "permalink": "/knowledge-base/tags/turnstile",
      "count": 3,
      "description": "Cloudflare Turnstile 的攻防两侧",
      "parent": "逆向与风控",
      "aliases": [
        "Turnstile防御"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "检测面建模",
      "slug": "检测面建模",
      "permalink": "/knowledge-base/tags/检测面建模",
      "count": 2,
      "description": "攻击者与防御者视角的信号建模",
      "parent": "逆向与风控",
      "aliases": [
        "事件可信度",
        "风控"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "评测",
      "slug": "评测",
      "permalink": "/knowledge-base/tags/评测",
      "count": 2,
      "description": "能力与效果的量化评估",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "上下文工程",
      "slug": "上下文工程",
      "permalink": "/knowledge-base/tags/上下文工程",
      "count": 2,
      "description": "上下文窗口的构造、压缩与组织",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Agent架构",
      "slug": "agent架构",
      "permalink": "/knowledge-base/tags/agent架构",
      "count": 2,
      "description": "Agent 系统的分层与模块解耦设计",
      "parent": "AI Agent",
      "aliases": [
        "Agent平台",
        "基础设施"
      ],
      "root": "AI Agent"
    },
    {
      "label": "AI工具",
      "slug": "ai工具",
      "permalink": "/knowledge-base/tags/ai工具",
      "count": 2,
      "description": "AI 辅助开发的工具链",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "C++",
      "slug": "c",
      "permalink": "/knowledge-base/tags/c",
      "count": 2,
      "description": "C++ 语言、范式与标准演进",
      "parent": "编程语言",
      "aliases": [
        "现代C++",
        "C++20"
      ],
      "root": "编程语言"
    },
    {
      "label": "Codex",
      "slug": "codex",
      "permalink": "/knowledge-base/tags/codex",
      "count": 2,
      "description": "OpenAI Codex CLI 的使用与观察",
      "parent": "Harness",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "MCP",
      "slug": "mcp",
      "permalink": "/knowledge-base/tags/mcp",
      "count": 2,
      "description": "Model Context Protocol 与其生态",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "Multica",
      "slug": "multica",
      "permalink": "/knowledge-base/tags/multica",
      "count": 2,
      "description": "Multica 多智能体协作平台",
      "parent": "多智能体",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "Python",
      "slug": "python",
      "permalink": "/knowledge-base/tags/python",
      "count": 2,
      "description": "Python 语言与生态",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "编译期多态",
      "slug": "编译期多态",
      "permalink": "/knowledge-base/tags/编译期多态",
      "count": 1,
      "description": "模板元编程与编译期计算",
      "parent": "C++",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "电脑包",
      "slug": "电脑包",
      "permalink": "/knowledge-base/tags/电脑包",
      "count": 1,
      "description": "电脑包的容量与结构",
      "parent": "选购指标",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "短视频",
      "slug": "短视频",
      "permalink": "/knowledge-base/tags/短视频",
      "count": 1,
      "description": "短视频的内容形态与影响",
      "parent": "生活杂谈",
      "aliases": [
        "想法探索"
      ],
      "root": "生活杂谈"
    },
    {
      "label": "检索",
      "slug": "检索",
      "permalink": "/knowledge-base/tags/检索",
      "count": 1,
      "description": "Agent 的外部检索与 RAG 链路",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "可复现性",
      "slug": "可复现性",
      "permalink": "/knowledge-base/tags/可复现性",
      "count": 1,
      "description": "结果可被稳定复现",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "浏览器指纹",
      "slug": "浏览器指纹",
      "permalink": "/knowledge-base/tags/浏览器指纹",
      "count": 1,
      "description": "浏览器与 TLS 指纹的构成和识别",
      "parent": "逆向与风控",
      "aliases": [
        "TLS指纹"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "浏览器自动化",
      "slug": "浏览器自动化",
      "permalink": "/knowledge-base/tags/浏览器自动化",
      "count": 1,
      "description": "Playwright 等浏览器自动化手段",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "毛选方法论",
      "slug": "毛选方法论",
      "permalink": "/knowledge-base/tags/毛选方法论",
      "count": 1,
      "description": "用毛选的方法分析现实问题",
      "parent": "生活杂谈",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "逆向工程",
      "slug": "逆向工程",
      "permalink": "/knowledge-base/tags/逆向工程",
      "count": 1,
      "description": "逆向分析的方法与经验",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "爬虫",
      "slug": "爬虫",
      "permalink": "/knowledge-base/tags/爬虫",
      "count": 1,
      "description": "网络数据采集与解析",
      "parent": "Python",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "凭证管理",
      "slug": "凭证管理",
      "permalink": "/knowledge-base/tags/凭证管理",
      "count": 1,
      "description": "密钥与凭据的存放和轮换",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "前端",
      "slug": "前端",
      "permalink": "/knowledge-base/tags/前端",
      "count": 1,
      "description": "Web 前端框架与交互实现",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "前端动画",
      "slug": "前端动画",
      "permalink": "/knowledge-base/tags/前端动画",
      "count": 1,
      "description": "交互动效与动画实现",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "数据面",
      "slug": "数据面",
      "permalink": "/knowledge-base/tags/数据面",
      "count": 1,
      "description": "数据面与控制面的职责切分",
      "parent": "Agent架构",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "通勤",
      "slug": "通勤",
      "permalink": "/knowledge-base/tags/通勤",
      "count": 1,
      "description": "通勤场景下的取舍",
      "parent": "选购指标",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "协程",
      "slug": "协程",
      "permalink": "/knowledge-base/tags/协程",
      "count": 1,
      "description": "协程模型与异步调度",
      "parent": "C++",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "选购指标",
      "slug": "选购指标",
      "permalink": "/knowledge-base/tags/选购指标",
      "count": 1,
      "description": "买东西时真正该看的指标",
      "parent": "生活杂谈",
      "aliases": [
        "商品选购"
      ],
      "root": "生活杂谈"
    },
    {
      "label": "验证码求解",
      "slug": "验证码求解",
      "permalink": "/knowledge-base/tags/验证码求解",
      "count": 1,
      "description": "验证码识别与自动化求解",
      "parent": "逆向与风控",
      "aliases": [
        "AI验证码求解"
      ],
      "root": "逆向与风控"
    },
    {
      "label": "异步任务",
      "slug": "异步任务",
      "permalink": "/knowledge-base/tags/异步任务",
      "count": 1,
      "description": "异步任务的组织与调度",
      "parent": "协程",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "语言特性",
      "slug": "语言特性",
      "permalink": "/knowledge-base/tags/语言特性",
      "count": 1,
      "description": "语言层面的特性与设计取舍",
      "parent": "编程语言",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "约束解码",
      "slug": "约束解码",
      "permalink": "/knowledge-base/tags/约束解码",
      "count": 1,
      "description": "用语法/结构约束模型输出格式",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "增量沉淀",
      "slug": "增量沉淀",
      "permalink": "/knowledge-base/tags/增量沉淀",
      "count": 1,
      "description": "只追加不重写的沉淀方式",
      "parent": "记忆系统",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "注意力",
      "slug": "注意力",
      "permalink": "/knowledge-base/tags/注意力",
      "count": 1,
      "description": "注意力被如何捕获与消耗",
      "parent": "生活杂谈",
      "aliases": [],
      "root": "生活杂谈"
    },
    {
      "label": "自建部署",
      "slug": "自建部署",
      "permalink": "/knowledge-base/tags/自建部署",
      "count": 1,
      "description": "自托管服务与网络配置",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "组件库",
      "slug": "组件库",
      "permalink": "/knowledge-base/tags/组件库",
      "count": 1,
      "description": "可复用 UI 组件与其设计",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "Bot Defense",
      "slug": "bot-defense",
      "permalink": "/knowledge-base/tags/bot-defense",
      "count": 1,
      "description": "产品侧的反爬与人机策略",
      "parent": "逆向与风控",
      "aliases": [],
      "root": "逆向与风控"
    },
    {
      "label": "KV Cache",
      "slug": "kv-cache",
      "permalink": "/knowledge-base/tags/kv-cache",
      "count": 1,
      "description": "注意力键值缓存与推理优化",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "LLM",
      "slug": "llm",
      "permalink": "/knowledge-base/tags/llm",
      "count": 1,
      "description": "大语言模型的能力边界与基本原理",
      "parent": "AI Agent",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "OAuth",
      "slug": "o-auth",
      "permalink": "/knowledge-base/tags/o-auth",
      "count": 1,
      "description": "OAuth 授权流程与令牌",
      "parent": "工程与工具",
      "aliases": [],
      "root": "工程与工具"
    },
    {
      "label": "react",
      "slug": "react",
      "permalink": "/knowledge-base/tags/react",
      "count": 1,
      "description": "React 及其生态组件",
      "parent": "前端",
      "aliases": [],
      "root": "编程语言"
    },
    {
      "label": "Tokenization",
      "slug": "tokenization",
      "permalink": "/knowledge-base/tags/tokenization",
      "count": 1,
      "description": "分词与 token 化对模型行为的影响",
      "parent": "LLM",
      "aliases": [],
      "root": "AI Agent"
    },
    {
      "label": "编程语言",
      "slug": "编程语言",
      "permalink": "/knowledge-base/tags/编程语言",
      "count": 0,
      "description": "语言本身的特性、范式与技术选型",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "工程与工具",
      "slug": "工程与工具",
      "permalink": "/knowledge-base/tags/工程与工具",
      "count": 0,
      "description": "开发工具链、部署、协作与可复现性",
      "parent": "",
      "aliases": [],
      "root": ""
    },
    {
      "label": "生活杂谈",
      "slug": "生活杂谈",
      "permalink": "/knowledge-base/tags/生活杂谈",
      "count": 0,
      "description": "个人生活、选购与读书杂谈",
      "parent": "",
      "aliases": [],
      "root": ""
    }
  ],
  "docs": [
    {
      "id": "AI/记忆/Agent-Memory框架选型",
      "title": "Agent Memory 选型指南: 五大范式、评测水分与四个必补动作",
      "description": "NOTE 同一个记忆框架, 在自家 benchmark 上可以报到 94.4 分 —— 而这个数字来自厂商托管平台的自测. 更麻烦的是: 同一类系统换一套测试脚手架, 分数能相差几十个百分点, 变量既不是模型也不是产品, 而是 谁写的评测代码 . 那么问题就不是\"该买哪个\", 而是: 在一个连分数都不可比的领域里, 选",
      "permalink": "/knowledge-base/AI/记忆/Agent-Memory框架选型",
      "date": "2026-09-13",
      "tags": [
        "AI Agent",
        "记忆系统",
        "技术选型",
        "评测"
      ]
    },
    {
      "id": "AI/记忆/obsidian-second-brain",
      "title": "obsidian-second-brain 全解: 一个会自我重写的 AI 知识库",
      "description": "NOTE 你的笔记库在半年后会比今天更聪明吗? 大多数\"第二大脑\"的答案是不会 —— 它们只是一个更整齐的文件柜: 放进去的东西原样躺着, 三个月前的决策和昨天的决策互相矛盾, 而没有任何人知道. obsidian second brain 想换掉这个前提: 知识库不是往里面加东西, 而是围绕新信息重写自己 . 那么,",
      "permalink": "/knowledge-base/AI/记忆/obsidian-second-brain",
      "date": "2026-09-13",
      "tags": [
        "记忆系统",
        "知识库",
        "Skill",
        "AI Agent"
      ]
    },
    {
      "id": "AI/检索/自建Agent检索栈与凭证治理",
      "title": "自建 Agent 检索栈: 本地化边界、凭证治理与可用性证明",
      "description": "NOTE 给 Agent 接检索, 最省事的做法永远是\"买一个搜索 API 然后填 key\". 可一旦把约束换成\"尽量完全本地自建\"和\"凭证配置必须体面\", 整个方案的形态就变了 —— 而且变的不只是选型. 更反直觉的是: 决定这套栈能不能长期活下来的, 往往不是检索算法, 而是 token 过期那一刻用户要面对多少摩",
      "permalink": "/knowledge-base/AI/检索/自建Agent检索栈与凭证治理",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "检索",
        "MCP",
        "自建部署",
        "OAuth",
        "凭证管理"
      ]
    },
    {
      "id": "AI/Skill/Agent-Skill编写最佳实践",
      "title": "Agent Skill 编写最佳实践: 上下文预算、触发工程与可证伪的验证",
      "description": "NOTE 为什么一个精心写好的 skill 会从来不被触发, 而一个写得普通的 skill 却总被误触发? 决定这件事的, 甚至不是它的正文. 更反直觉的是: 命名不合法、描述缺失、正文超预算 —— 这些失败 没有一个会报错 . skill 只是安静地从目录里消失, 而模型既看不到错误, 也分不清\"不存在\"与\"写错了\"",
      "permalink": "/knowledge-base/AI/Skill/Agent-Skill编写最佳实践",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "上下文工程",
        "提示词工程",
        "工程实践"
      ]
    },
    {
      "id": "AI/Skill/SkillOpt把skill当参数训练",
      "title": "SkillOpt: 把 skill 文档当参数来训练, 以及它在规范与可复现性上的边界",
      "description": "NOTE 如果一份 skill 文档写得不好, 为什么不能像调参一样把它\"训\"好? SKILL.md 是纯文本, 模型权重可以冻结, 任务分数就是现成的损失函数 —— 这条路听起来几乎无懈可击. 但真正的问题在另一头: 一个只会看任务分数的优化器, 知不知道 skill 该长成什么形状? 它怎么判断\"变得更长\"是进步还",
      "permalink": "/knowledge-base/AI/Skill/SkillOpt把skill当参数训练",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "提示词工程",
        "可复现性",
        "评测"
      ]
    },
    {
      "id": "AI/记忆/自维护可插拔记忆层设计",
      "title": "自维护可插拔记忆层设计: 一次对比市面方案后的收敛",
      "description": "NOTE 一个 AI 在 A 项目里踩过的坑, 为什么到了 B 项目还要再踩一遍? 多数\"记忆\"系统只做到了同一工作区内的召回 —— 出了这个会话, 经验就归零. 真正想要的是另一件事: 让一次具体事故自动上升成一条对 所有 项目都成立的规则. 那么, 一个既能被任何 harness 读写、又能自己把经验拔高的记忆层,",
      "permalink": "/knowledge-base/AI/记忆/自维护可插拔记忆层设计",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH预设提示词全解",
      "title": "DeepSeek Harness 提示词全解: 四个预设与每一步投递",
      "description": "NOTE 同一句\"你好\", 为什么在标准模式和极简模式里会被送出完全不同的请求头? 提示词在那台运行时里不是一段文字, 而是一组按 order 拼装、按预设挂载、按步骤重建的资产. 更反常识的是: 压缩指令不是另写的摘要 system prompt, 而是 追加在回放会话最后的一条 user 消息 —— 只为让这次旁路",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH预设提示词全解",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH",
        "提示词工程"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH-Agent-Loop源码剖析",
      "title": "DSH Agent Loop 源码剖析",
      "description": "NOTE 用户说一句\"用 echo 回显 ping\", 会话里到底发生了什么? 没有聊天记录, 只有一条 turn/start step/start tool/call tool/result step/end 的事件串, 模型每次看到的历史都是现场推导出来的. 更反常识的是: 一次 step/start 到 step",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH-Agent-Loop源码剖析",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH"
      ]
    },
    {
      "id": "AI/Agent-Harness/DSH/DSH-Runtime设计思想插件树与事件日志",
      "title": "DeepSeek Harness设计思想: 插件树与事件日志",
      "description": "NOTE 一个 agent 最贵的时刻, 不是模型答错, 而是它在崩溃重启后 把已经改过的文件又改了一遍 . 要避免这件事, 光有\"聊天记录\"远远不够: 系统必须能回答三个问题 —— 这个能力是谁给的、这次副作用到底发生了没有、模型究竟看见过什么. DeepSeek Harness 把这些归属全部收进两根支柱: 插件树",
      "permalink": "/knowledge-base/AI/Agent-Harness/DSH/DSH-Runtime设计思想插件树与事件日志",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "Harness",
        "DSH"
      ]
    },
    {
      "id": "杂谈/短视频-精神鸦片",
      "title": "短视频=精神鸦片: 用毛选方法论解构注意力成瘾",
      "description": "NOTE 卸载了又装回来, 明明想早点睡却刷到凌晨三点 — 这真的只是意志力不够吗? 如果让你停不下来的不是手机, 而是一套被反复测试过的刺激设计, 那你该戒的对象又是谁? 0x00 背景 你是否有过这样的经历: 反复卸载短视频 App, 又反复装回来; 越想早点睡, 越是刷到凌晨三点; 遇到一点困难就想放弃, 然后不",
      "permalink": "/knowledge-base/杂谈/短视频-精神鸦片",
      "date": "2026-09-04",
      "tags": [
        "短视频",
        "注意力",
        "毛选方法论"
      ]
    },
    {
      "id": "AI/记忆/对话记忆与知识库增量沉淀",
      "title": "AI Agent 对话记忆与知识库增量沉淀设计",
      "description": "NOTE 你的 Agent 记住的应该是什么? 是一堆日志, 还是一条 能从过去通向当下决策的链子 ? 如果一个用户今天改了偏好、明天打断纠正了你, 你的系统是\"秒更新又能回答昨天\", 还是两者顾此失彼? 日志该追加、知识该分视图、现状该覆盖、历史该双时态、错误该变成 skill —— 而这一切不始于某张精美的架构图,",
      "permalink": "/knowledge-base/AI/记忆/对话记忆与知识库增量沉淀",
      "date": "2026-08-31",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库",
        "增量沉淀"
      ]
    },
    {
      "id": "程序语言/Python/Python语言核心特性调研",
      "title": "Python 语言核心特性调研",
      "description": "NOTE 一门语言\"容易上手\"究竟是优点还是陷阱? Python 用缩进代替花括号、用动态类型代替类型声明, 换来的是更短的脚本和更快的原型. 但如果一门语言的入门成本降低了, 它把复杂度推到了哪里? 0x00 一句话总结 Python is an easy to learn, powerful programming",
      "permalink": "/knowledge-base/程序语言/Python/Python语言核心特性调研",
      "date": "2026-08-30",
      "tags": [
        "Python",
        "语言特性",
        "技术选型"
      ]
    },
    {
      "id": "AI/AI逆向/多模态AI通用验证码求解服务",
      "title": "用AI从零实现通用验证码求解服务:OhMyCaptcha原理剖析",
      "description": "NOTE 当\"看懂图片\"这件事从传统 CV 的模板匹配/图像处理, 变成\"直接问多模态大模型\", 验证码求解的架构会简化多少? 代价又是什么? 0x00 背景 原文剖析开源项目 OhMyCaptcha: 用 Playwright + 多模态大模型构建覆盖 19 种验证码类型的自托管求解服务. 它值得被单独拆解的三个理由",
      "permalink": "/knowledge-base/AI/AI逆向/多模态AI通用验证码求解服务",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "验证码求解",
        "浏览器自动化"
      ]
    },
    {
      "id": "AI/AI逆向/真实浏览器扩展的验证机制拆解",
      "title": "Infinitoai与Turnstile:一次浏览器验证机制的技术拆解",
      "description": "NOTE 一个\"会点复选框\"的脚本和一个\"看起来像真人\"的脚本, 差距究竟在哪一层? 是注入时机, 是事件来源, 还是页面状态感知? 0x00 背景 原文以开源项目 Infinitoai 一个 Chrome 扩展 为切入点, 不讲\"怎么一把梭\", 而是拆解 真实浏览器里的扩展为什么比普通脚本更接近真人环境 . 它值得被",
      "permalink": "/knowledge-base/AI/AI逆向/真实浏览器扩展的验证机制拆解",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "检测面建模"
      ]
    },
    {
      "id": "AI/AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "title": "深入理解Cloudflare过盾原理:无需AI从零实现CFTurnstile绕过",
      "description": "NOTE 当一个系统反复向你证明\"你是机器人\"时, 它到底在看什么? 是屏幕上的图片, 还是你浏览器内核里每一个不自洽的细节? 0x00 背景 Turnstile 与传统验证码有一个根本差异: 它几乎不出视觉题. 没有扭曲字母, 也没有九宫格选图, 只是在后台收集你浏览器的环境信号, 再判断\"这个环境是不是一个真实的人",
      "permalink": "/knowledge-base/AI/AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "浏览器指纹"
      ]
    },
    {
      "id": "AI/AI逆向/Turnstile防御面分析与误判权衡",
      "title": "CloudflareTurnstile防御分析:浏览器信号检测面与误判权衡",
      "description": "NOTE 如果一个验证组件注定无法 100% 拦截自动化, 那它存在的意义是什么? 是\"绝对正确\", 还是\"把攻击成本抬到不值得\"? 0x00 背景 原文站在防御者视角, 分析 Turnstile 为什么有效、依赖哪些信号、网站在安全与误判之间怎么取舍. 它值得被单独拆解的三个理由: 它是四篇中唯一\"站在对手 防御方 ",
      "permalink": "/knowledge-base/AI/AI逆向/Turnstile防御面分析与误判权衡",
      "date": "2026-08-26",
      "tags": [
        "逆向与风控",
        "Turnstile",
        "检测面建模",
        "Bot Defense"
      ]
    },
    {
      "id": "AI/基础/Agent要懂的LLM基础知识",
      "title": "Agent要懂的LLM基础知识",
      "description": "NOTE 一个 Agent 聊到第二十轮突然不守规矩, 第一百零一次工具调用吐出坏 JSON —— 第一反应通常是\"框架有 bug\", 可如果问题根本不在框架里呢? 温度、分词、注意力这些看起来离业务很远的东西, 决定了 Agent 的成本、延迟与稳定边界; 把它们当成玄学调参, 就只会在同一个坑里反复摔. 0x00 ",
      "permalink": "/knowledge-base/AI/基础/Agent要懂的LLM基础知识",
      "date": "2026-08-10",
      "tags": [
        "AI Agent",
        "LLM",
        "Tokenization",
        "KV Cache",
        "约束解码"
      ]
    },
    {
      "id": "AI/Agent架构/AI-Agent设计原理与工程实践",
      "title": "AI Agent设计原理与工程实践",
      "description": "NOTE 同一个模型, 换一套外壳, 有的 Agent 能可靠跑完一单退款, 有的却在第三步就编出一句\"已经帮你处理好了\"——差距究竟在模型里, 还是在模型之外? 上下文、工具、约束、验证、纠正, 每一环都决定它落地时是助手还是负担; 这篇文章要问的是, 把这些环节拼成生产可用的 Agent, 工程上到底要付出什么. ",
      "permalink": "/knowledge-base/AI/Agent架构/AI-Agent设计原理与工程实践",
      "date": "2026-08-10",
      "tags": [
        "AI Agent",
        "Agent架构",
        "上下文工程",
        "多智能体",
        "工程实践"
      ]
    },
    {
      "id": "工具链/从打野到注册机与AI工具链",
      "title": "从打野到注册机: 一条真实项目工具链的工程化学习",
      "description": "NOTE 一次注册流程的练习, 为什么会走到浏览器自动化、邮箱池、代理网关、FastAPI 封装, 最后停在 Codex 与 Skills 上? 因为真正被复用的从来不是\"注册机\"这个目标, 而是逐层补齐契约的方法: 谁给输入、谁持有状态、失败由谁负责、证据留在哪里. 这条帖子把资源搜集、协议探查、账号与网络出口、服务",
      "permalink": "/knowledge-base/工具链/从打野到注册机与AI工具链",
      "date": "2026-08-02",
      "tags": [
        "AI工具",
        "逆向工程",
        "Codex",
        "MCP"
      ]
    },
    {
      "id": "AI/Agent架构/Agent平台数据面灵活解耦",
      "title": "Agent平台数据面灵活解耦",
      "description": "NOTE 如果所有 Agent 都跑在同一套基础设施上, 那么当某个业务要求更高隔离、另一套集群容量见底、某个客户坚持私有网络部署时, 平台还剩多少选择? \"一个控制面管理多个数据面\"听起来只是多了一层抽象, 可它决定的其实是平台能不能跨机器、跨集群、跨云落地. 0x00 背景 Agent 平台通常由控制面和数据面组成",
      "permalink": "/knowledge-base/AI/Agent架构/Agent平台数据面灵活解耦",
      "date": "2026-07-15",
      "tags": [
        "AI Agent",
        "Agent架构",
        "数据面"
      ]
    },
    {
      "id": "工具链/RTK项目使用说明与Codex本地心得",
      "title": "RTK项目使用说明与Codex本地心得",
      "description": "NOTE 你喂给 AI 编程助手的每一条 shell 输出, 有多少是它真正需要看见的? 一次全量测试就能刷掉几千 token, 其中大半只是\"通过了\". RTK Rust Token Killer 的答案不是让模型少跑命令, 而是在命令输出进入上下文之前先过滤一层; 但压缩过的输出 不再等于原始事实全集 . 于是真正",
      "permalink": "/knowledge-base/工具链/RTK项目使用说明与Codex本地心得",
      "date": "2026-07-05",
      "tags": [
        "AI工具",
        "Codex",
        "Harness"
      ]
    },
    {
      "id": "生活/电脑包选购指标",
      "title": "电脑包选购指标",
      "description": "NOTE 为什么商品页上「大容量」「商务」「多功能」「轻便」每一条都挑不出错, 到手却可能塞不进电脑、勒着肩膀、功能多到空包就沉? 如果我根本不知道自己每天要装什么、电脑实际多宽, 那我看的到底是包, 还是一串没人能验证的形容词? 0x00 背景 电脑包很容易被商品标题误导: 「大容量」「商务」「旅行」「多功能」「轻便",
      "permalink": "/knowledge-base/生活/电脑包选购指标",
      "date": "2026-07-05",
      "tags": [
        "选购指标",
        "电脑包",
        "通勤"
      ]
    },
    {
      "id": "AI/多智能体/Multica-agent协作与上下文机制",
      "title": "Multica agent协作与上下文机制",
      "description": "NOTE 在一个工作区里让一个 agent 去唤起另一个 agent 继续干活, 听起来只需要一句 @ ; 但它最容易长成的却是停不下来的成本循环 —— 谁该被叫醒, 被叫醒时它究竟带着哪些上下文? 更反直觉的是: 决定一次运行的并不是上一条评论, 而是 runtime 为这次触发临时注入的任务 brief. agen",
      "permalink": "/knowledge-base/AI/多智能体/Multica-agent协作与上下文机制",
      "date": "2026-07-05",
      "tags": [
        "多智能体",
        "Multica",
        "AI Agent"
      ]
    },
    {
      "id": "AI/多智能体/Multica智能体模板与小队编排skills调研",
      "title": "Multica智能体模板与小队编排skills调研",
      "description": "NOTE 用户说\"这些技术栈都可以用\", 一个 agent 会怎么理解? 大概率是把它们全部装进方案 —— 因为它把\"可用\"读成了\"必用\". 同一个问题在编排上还会再出现一次: 当\"组一个小队\"被理解成\"把成员都 @ 一遍\", 平台实际只唤醒了一个 leader, 其余人从未收到任务. 那么, 一套真正可交付的智能体编",
      "permalink": "/knowledge-base/AI/多智能体/Multica智能体模板与小队编排skills调研",
      "date": "2026-07-05",
      "tags": [
        "多智能体",
        "Multica",
        "Skill",
        "AI Agent"
      ]
    },
    {
      "id": "程序语言/现代C++/现代C++编译期多态审视",
      "title": "现代C++编译期多态审视",
      "description": "NOTE 如果编译器已经知道你程序里只会出现哪几种类型, 那么每一次调用都穿过一层运行期间接, 究竟是在为谁保留可能性? 「C++20 之后可以彻底抛弃 virtual 」更像一句口号 —— 它成立的前提 类型集合封闭、二进制与源码一起构建 比结论本身重要得多. 这篇文章要问的是: 编译期多态把哪些成本挪走了, 又把哪",
      "permalink": "/knowledge-base/程序语言/现代C++/现代C++编译期多态审视",
      "date": "2026-07-04",
      "tags": [
        "C++",
        "编译期多态",
        "工程实践"
      ]
    },
    {
      "id": "程序语言/Python/Python爬虫库选型调研",
      "title": "Python爬虫库选型调研",
      "description": "NOTE 当准备写一个 Python 爬虫时, 真正需要先回答的问题不是「哪个库最强」, 而是: 目标页面是否静态? 是否需要登录和浏览器交互? 采集规模是否需要调度、重试和持久化? 最终要的是结构化字段, 还是网页正文? 0x00 背景 Python 爬虫生态里常见库很多, 但它们并不在同一个层级竞争: reques",
      "permalink": "/knowledge-base/程序语言/Python/Python爬虫库选型调研",
      "date": "2026-07-04",
      "tags": [
        "Python",
        "爬虫",
        "技术选型"
      ]
    },
    {
      "id": "程序语言/Web前端/react-bits分门别类学习",
      "title": "react-bits 分门别类学习",
      "description": "NOTE 一个动效组件库值得学的地方, 通常不在于它提供了哪些效果, 而在于它怎么让 134 个组件各自被找得到、装得上、换得掉. 如果换成你来组织一份「可复制源码」的组件集合, 会用一份元数据表同时驱动文档、registry 和 AI 索引, 还是给四种技术栈各维护一套? PPT ppt — react bits 分",
      "permalink": "/knowledge-base/程序语言/Web前端/react-bits分门别类学习",
      "date": "2026-07-04",
      "tags": [
        "react",
        "前端",
        "前端动画",
        "组件库"
      ]
    },
    {
      "id": "程序语言/现代C++/HXLibs编写串行协程调度器",
      "title": "HXLibs 协程串行调度器探索",
      "description": "NOTE 一个协程被恢复的那一刻, 它究竟\"站在\"哪里? 无栈协程本身只是一段可暂停的状态机, 真正决定行为的是 恢复它的那一瞬间, 控制流从哪条线上继续 . 把这条线收拢成一条, 串行调度就成立了; 一旦想不清它, 析构顺序、悬空引用与玄学段错误便会一起找上门. 下面这三轮迭代, 其实一直在反复回答同一个问题: 谁持",
      "permalink": "/knowledge-base/程序语言/现代C++/HXLibs编写串行协程调度器",
      "date": "2026-06-04",
      "tags": [
        "C++",
        "协程",
        "异步任务"
      ]
    },
    {
      "id": "关于",
      "title": "关于",
      "description": "TIP 这里是 HXLoLi 的 AI 沉淀知识库. 作者懒得写笔记的时候, 内容会先沉淀在这里, 以免污染正式笔记. 站内笔记按统一的写作规范与工作流起草, 每一篇都经作者复核后才提交 —— 你能读到的内容都经过人工确认, 而非模型的一次性输出. 目标: 减少编写笔记的时间. 非期望: 使用 AI 瞎jb产出.",
      "permalink": "/knowledge-base/关于",
      "date": "2026-06-04",
      "tags": []
    }
  ],
  "generatedAt": "2026-09-13T15:45:19.462Z"
};
