// Auto-generated by tag-index-plugin — do not edit manually.
export interface AiDocTagInfo {
  /** 标签原文 (frontmatter 里的写法) */
  label: string;
  /** 与内容插件一致的 slug (lodash.kebabCase) */
  slug: string;
  /** 标签详情页的站内路径 (不含 baseUrl) */
  permalink: string;
  /** 打这个标签的笔记数 */
  count: number;
  /** 注册表 ai-docs/.hx-tags.toml 里的人工描述, 可为空 */
  description: string;
  /** 注册表里登记的同义写法 */
  aliases: string[];
}

export interface AiDocEntry {
  /** 文档 slug (与内容插件保持一致, 目录数字前缀已去掉) */
  id: string;
  title: string;
  description: string;
  /** 站内路径 (不含 baseUrl) */
  permalink: string;
  /** YYYY-MM-DD */
  date: string;
  /** 这篇笔记的标签原文 */
  tags: string[];
}

export interface AiDocTagIndex {
  tags: AiDocTagInfo[];
  docs: AiDocEntry[];
  generatedAt: string;
}

export const aiDocTagIndex: AiDocTagIndex = {
  "tags": [
    {
      "label": "AI Agent",
      "slug": "ai-agent",
      "permalink": "/knowledge-base/tags/ai-agent",
      "count": 13,
      "description": "",
      "aliases": []
    },
    {
      "label": "AI逆向",
      "slug": "ai逆向",
      "permalink": "/knowledge-base/tags/ai逆向",
      "count": 4,
      "description": "",
      "aliases": []
    },
    {
      "label": "Harness",
      "slug": "harness",
      "permalink": "/knowledge-base/tags/harness",
      "count": 4,
      "description": "",
      "aliases": []
    },
    {
      "label": "Skill",
      "slug": "skill",
      "permalink": "/knowledge-base/tags/skill",
      "count": 4,
      "description": "",
      "aliases": []
    },
    {
      "label": "项目学习",
      "slug": "项目学习",
      "permalink": "/knowledge-base/tags/项目学习",
      "count": 3,
      "description": "",
      "aliases": []
    },
    {
      "label": "知识库",
      "slug": "知识库",
      "permalink": "/knowledge-base/tags/知识库",
      "count": 3,
      "description": "",
      "aliases": []
    },
    {
      "label": "DSH",
      "slug": "dsh",
      "permalink": "/knowledge-base/tags/dsh",
      "count": 3,
      "description": "",
      "aliases": []
    },
    {
      "label": "003-编程语言",
      "slug": "003-编程语言",
      "permalink": "/knowledge-base/tags/003-编程语言",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "工程实践",
      "slug": "工程实践",
      "permalink": "/knowledge-base/tags/工程实践",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "工程协作",
      "slug": "工程协作",
      "permalink": "/knowledge-base/tags/工程协作",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "记忆系统",
      "slug": "记忆系统",
      "permalink": "/knowledge-base/tags/记忆系统",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "评测",
      "slug": "评测",
      "permalink": "/knowledge-base/tags/评测",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "上下文工程",
      "slug": "上下文工程",
      "permalink": "/knowledge-base/tags/上下文工程",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "增量沉淀",
      "slug": "增量沉淀",
      "permalink": "/knowledge-base/tags/增量沉淀",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "Codex",
      "slug": "codex",
      "permalink": "/knowledge-base/tags/codex",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "MCP",
      "slug": "mcp",
      "permalink": "/knowledge-base/tags/mcp",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "Multica",
      "slug": "multica",
      "permalink": "/knowledge-base/tags/multica",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "Turnstile",
      "slug": "turnstile",
      "permalink": "/knowledge-base/tags/turnstile",
      "count": 2,
      "description": "",
      "aliases": []
    },
    {
      "label": "编译期多态",
      "slug": "编译期多态",
      "permalink": "/knowledge-base/tags/编译期多态",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "测试",
      "slug": "测试",
      "permalink": "/knowledge-base/tags/测试",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "插件化",
      "slug": "插件化",
      "permalink": "/knowledge-base/tags/插件化",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "程序性记忆",
      "slug": "程序性记忆",
      "permalink": "/knowledge-base/tags/程序性记忆",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "电脑包",
      "slug": "电脑包",
      "permalink": "/knowledge-base/tags/电脑包",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "短视频",
      "slug": "短视频",
      "permalink": "/knowledge-base/tags/短视频",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "多模态大模型",
      "slug": "多模态大模型",
      "permalink": "/knowledge-base/tags/多模态大模型",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "多智能体",
      "slug": "多智能体",
      "permalink": "/knowledge-base/tags/多智能体",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "泛化",
      "slug": "泛化",
      "permalink": "/knowledge-base/tags/泛化",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "风控",
      "slug": "风控",
      "permalink": "/knowledge-base/tags/风控",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "基础设施",
      "slug": "基础设施",
      "permalink": "/knowledge-base/tags/基础设施",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "技术选型",
      "slug": "技术选型",
      "permalink": "/knowledge-base/tags/技术选型",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "检测面建模",
      "slug": "检测面建模",
      "permalink": "/knowledge-base/tags/检测面建模",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "检索",
      "slug": "检索",
      "permalink": "/knowledge-base/tags/检索",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "接口设计",
      "slug": "接口设计",
      "permalink": "/knowledge-base/tags/接口设计",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "可插拔",
      "slug": "可插拔",
      "permalink": "/knowledge-base/tags/可插拔",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "可复现性",
      "slug": "可复现性",
      "permalink": "/knowledge-base/tags/可复现性",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "浏览器验证机制",
      "slug": "浏览器验证机制",
      "permalink": "/knowledge-base/tags/浏览器验证机制",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "浏览器指纹",
      "slug": "浏览器指纹",
      "permalink": "/knowledge-base/tags/浏览器指纹",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "浏览器自动化",
      "slug": "浏览器自动化",
      "permalink": "/knowledge-base/tags/浏览器自动化",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "毛选方法论",
      "slug": "毛选方法论",
      "permalink": "/knowledge-base/tags/毛选方法论",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "逆向工程",
      "slug": "逆向工程",
      "permalink": "/knowledge-base/tags/逆向工程",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "爬虫",
      "slug": "爬虫",
      "permalink": "/knowledge-base/tags/爬虫",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "平台架构",
      "slug": "平台架构",
      "permalink": "/knowledge-base/tags/平台架构",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "凭证管理",
      "slug": "凭证管理",
      "permalink": "/knowledge-base/tags/凭证管理",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "前端动画",
      "slug": "前端动画",
      "permalink": "/knowledge-base/tags/前端动画",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "商品选购",
      "slug": "商品选购",
      "permalink": "/knowledge-base/tags/商品选购",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "事件可信度",
      "slug": "事件可信度",
      "permalink": "/knowledge-base/tags/事件可信度",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "事件日志",
      "slug": "事件日志",
      "permalink": "/knowledge-base/tags/事件日志",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "数据面",
      "slug": "数据面",
      "permalink": "/knowledge-base/tags/数据面",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "双时态",
      "slug": "双时态",
      "permalink": "/knowledge-base/tags/双时态",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "提示词工程",
      "slug": "提示词工程",
      "permalink": "/knowledge-base/tags/提示词工程",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "提示词优化",
      "slug": "提示词优化",
      "permalink": "/knowledge-base/tags/提示词优化",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "通勤",
      "slug": "通勤",
      "permalink": "/knowledge-base/tags/通勤",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "现代C++",
      "slug": "现代c",
      "permalink": "/knowledge-base/tags/现代c",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "想法探索",
      "slug": "想法探索",
      "permalink": "/knowledge-base/tags/想法探索",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "协程",
      "slug": "协程",
      "permalink": "/knowledge-base/tags/协程",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "选购指标",
      "slug": "选购指标",
      "permalink": "/knowledge-base/tags/选购指标",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "异步任务",
      "slug": "异步任务",
      "permalink": "/knowledge-base/tags/异步任务",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "预设",
      "slug": "预设",
      "permalink": "/knowledge-base/tags/预设",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "源码",
      "slug": "源码",
      "permalink": "/knowledge-base/tags/源码",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "约束解码",
      "slug": "约束解码",
      "permalink": "/knowledge-base/tags/约束解码",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "注意力",
      "slug": "注意力",
      "permalink": "/knowledge-base/tags/注意力",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "自建部署",
      "slug": "自建部署",
      "permalink": "/knowledge-base/tags/自建部署",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "组件库",
      "slug": "组件库",
      "permalink": "/knowledge-base/tags/组件库",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Agent Runtime",
      "slug": "agent-runtime",
      "permalink": "/knowledge-base/tags/agent-runtime",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Agent平台",
      "slug": "agent平台",
      "permalink": "/knowledge-base/tags/agent平台",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "AI工具",
      "slug": "ai工具",
      "permalink": "/knowledge-base/tags/ai工具",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "AI验证码求解",
      "slug": "ai验证码求解",
      "permalink": "/knowledge-base/tags/ai验证码求解",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Bot Defense",
      "slug": "bot-defense",
      "permalink": "/knowledge-base/tags/bot-defense",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "C++",
      "slug": "c",
      "permalink": "/knowledge-base/tags/c",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "C++20",
      "slug": "c-20",
      "permalink": "/knowledge-base/tags/c-20",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "CF过盾",
      "slug": "cf过盾",
      "permalink": "/knowledge-base/tags/cf过盾",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Chrome扩展",
      "slug": "chrome扩展",
      "permalink": "/knowledge-base/tags/chrome扩展",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "CLI",
      "slug": "cli",
      "permalink": "/knowledge-base/tags/cli",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Compaction",
      "slug": "compaction",
      "permalink": "/knowledge-base/tags/compaction",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "HXLibs",
      "slug": "hx-libs",
      "permalink": "/knowledge-base/tags/hx-libs",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "KV Cache",
      "slug": "kv-cache",
      "permalink": "/knowledge-base/tags/kv-cache",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "LLM",
      "slug": "llm",
      "permalink": "/knowledge-base/tags/llm",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "OAuth",
      "slug": "o-auth",
      "permalink": "/knowledge-base/tags/o-auth",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Port-Adapter",
      "slug": "port-adapter",
      "permalink": "/knowledge-base/tags/port-adapter",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Prompt",
      "slug": "prompt",
      "permalink": "/knowledge-base/tags/prompt",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Python",
      "slug": "python",
      "permalink": "/knowledge-base/tags/python",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "react",
      "slug": "react",
      "permalink": "/knowledge-base/tags/react",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "RTK",
      "slug": "rtk",
      "permalink": "/knowledge-base/tags/rtk",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "TLS指纹",
      "slug": "tls指纹",
      "permalink": "/knowledge-base/tags/tls指纹",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Tokenization",
      "slug": "tokenization",
      "permalink": "/knowledge-base/tags/tokenization",
      "count": 1,
      "description": "",
      "aliases": []
    },
    {
      "label": "Turnstile防御",
      "slug": "turnstile防御",
      "permalink": "/knowledge-base/tags/turnstile防御",
      "count": 1,
      "description": "",
      "aliases": []
    }
  ],
  "docs": [
    {
      "id": "deck-embed-test",
      "title": "演示页挂载实测",
      "description": "NOTE 临时测试文档, 用于验证\"按相对路径 + 扩展名识别演示页\". 一、最简: 只给路径 PPT 二、指定默认展示第 3 页 PPT 3 三、指定主题 PPT 1 sakura 四、具名写法 PPT 页码=2 主题=hxloli 五、通用本地 HTML 老语法, iframe 历史 PPT 侧车 ppt",
      "permalink": "/knowledge-base/deck-embed-test",
      "date": "2026-09-12",
      "tags": [
        "测试"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/自建Agent检索栈与凭证治理",
      "title": "自建 Agent 检索栈: 本地化边界、凭证治理与可用性证明",
      "description": "0x00 背景 给 Agent 接检索, 很多人默认的做法是\"买一个搜索 API 然后填 key\". 但一旦把约束换成下面两条, 整个方案形态就变了: 1. 尽量完全本地自建 — 检索链路不依赖商业检索 API, 数据不出本机, 成本可预测, 不受第三方限流与条款变动摆布. 2. 凭证配置必须体面 — 社交平台终究要 ",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/自建Agent检索栈与凭证治理",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "MCP",
        "检索",
        "自建部署",
        "OAuth",
        "凭证管理",
        "评测"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/Agent-Skill编写最佳实践",
      "title": "Agent Skill 编写最佳实践: 上下文预算、触发工程与可证伪的验证",
      "description": "0x00 背景 大多数人写 skill 的方式是这样的: 把知道的都写进去, 写长了就删一点, 看起来完整就交差. 于是最常见的结果是两种 —— 要么这个 skill 永远不会被触发, 要么它把上下文窗口占满而收益极低 . 这两种失败有一个共同的、隐蔽的特征: 它们都不会报错 . 名字写错、触发条件写在正文里、正文长到",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/Agent-Skill编写最佳实践",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "上下文工程",
        "提示词工程",
        "工程实践"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/SkillOpt把skill当参数训练",
      "title": "SkillOpt: 把 skill 文档当参数来训练, 以及它在规范与可复现性上的边界",
      "description": "0x00 背景 给 agent 加能力, 主流做法是写一份 skill —— 一个目录, 里面有 SKILL.md 和可选的脚本与参考文件. 但写好一份 skill 很难, 于是出现了一类很自然的想法: 既然改提示词有效, 那能不能像训练神经网络一样\"训练\"这份 markdown? SkillOpt 是这类想法里工程化",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/SkillOpt把skill当参数训练",
      "date": "2026-09-11",
      "tags": [
        "AI Agent",
        "Skill",
        "提示词优化",
        "可复现性",
        "评测"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/自维护可插拔记忆层设计",
      "title": "自维护可插拔记忆层设计: 一次对比市面方案后的收敛",
      "description": "0x00 背景 要给 HXLoLi 的 AI 生态 DSH 为主, 未来可能还有 Codex/其他 CLI 配一套长期记忆层. 两个硬需求: 1. 所有 AI 都能读我的知识库 从任何工作区, 只要我允许 ; 2. 知识是关联/渐进/可推广的 —— 不只是 top k 相似度, 而是能从一个具体事故 例如\"后端队列并发",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/自维护可插拔记忆层设计",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库",
        "可插拔",
        "Port-Adapter",
        "泛化"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/DSH预设提示词全解",
      "title": "DeepSeek Harness 提示词全解: 四个预设与每一步投递",
      "description": "DeepSeek Harness 不是一个聊天机器人, 而是一台把\"提示词\"当作可插拔资产来组装的运行时. 本文逐字抄录这台运行时在每一步 实际投递给模型 的提示词: 系统提示词由哪些段 section 按什么顺序拼成, 每次用户消息后追加的运行时上下文快照长什么样, 每个工具的引导文本与描述原文, 以及 plan /",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/DSH预设提示词全解",
      "date": "2026-09-06",
      "tags": [
        "AI Agent",
        "DSH",
        "Harness",
        "Prompt",
        "预设"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/DeepSeek Harness Runtime设计思想插件树与事件日志",
      "title": "DeepSeek Harness设计思想: 插件树与事件日志",
      "description": "0x00 这篇文章要回答什么? 几十行代码就能写一个能跑的 agent: 收一条用户消息, 拼好提示词请求模型, 模型要调用工具就执行工具, 再把结果放回上下文. 可一旦这个 agent 要 连续工作、修改真实文件、崩溃之后接着完成 , 问题就不再是\"调用模型\"了: 模型调用到一半进程崩了怎么办? 工具已经改了文件, ",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/DeepSeek Harness Runtime设计思想插件树与事件日志",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "DSH",
        "Harness",
        "Agent Runtime",
        "插件化",
        "事件日志"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/DSH-Agent-Loop源码剖析",
      "title": "DSH Agent Loop 源码剖析",
      "description": "直接读 DeepSeek Harness 源码 packages/core/agent loop, 版本 0.1.x, monorepo: github.com/deepseek ai/dsh , 把 ReactLoopAgent 的驱动循环、事件日志、工具回灌与上下文压缩讲清楚. 图中每个节点都是真实代码里的方法名/",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/DSH-Agent-Loop源码剖析",
      "date": "2026-09-05",
      "tags": [
        "AI Agent",
        "DSH",
        "Harness",
        "源码",
        "Compaction"
      ]
    },
    {
      "id": "想法探索/短视频=精神鸦片用毛选解构注意力成瘾",
      "title": "短视频=精神鸦片: 用毛选方法论解构注意力成瘾",
      "description": "NOTE 本文提炼自 B 站视频《毛选实战局》一期节目 BV1Xv8x6uEqa , 拆解短视频成瘾的机制, 并借用毛选的方法论给出应对思路. 适合正在和短视频反复拉扯、想找回专注力的人阅读. 0x00 背景 你是否有过这样的经历: 反复卸载短视频 App, 又反复装回来; 越想早点睡, 越是刷到凌晨三点; 遇到一点困",
      "permalink": "/knowledge-base/想法探索/短视频=精神鸦片用毛选解构注意力成瘾",
      "date": "2026-09-04",
      "tags": [
        "想法探索",
        "短视频",
        "注意力",
        "毛选方法论"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/对话记忆与知识库增量沉淀",
      "title": "AI Agent 对话记忆与知识库增量沉淀设计",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 背景 要解决的问题 : 一个 Agent 如 AI 助手 / coding copilot 与用户长期交互, 会产生海量对话日志. 日志本身不是知识. 我们真正想要的, 是把日志里 对当前决策/复用有长期价值的信息 , 增量地固化成一个\"",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/对话记忆与知识库增量沉淀",
      "date": "2026-08-31",
      "tags": [
        "AI Agent",
        "记忆系统",
        "知识库",
        "增量沉淀",
        "双时态",
        "程序性记忆"
      ]
    },
    {
      "id": "知识沉淀/编程语言/Python语言/日常探索/AI驱动的视频调研与知识沉淀工作流",
      "title": "AI驱动的视频调研与知识沉淀工作流",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 一句话总结 待补充: 请基于采集材料凝练核心结论。 0x01 材料与可靠性 视频/音源: /tmp/brtest/e2e video sample.srt transcript: /home/hx/.dsh/dsh blog resear",
      "permalink": "/knowledge-base/知识沉淀/编程语言/Python语言/日常探索/AI驱动的视频调研与知识沉淀工作流",
      "date": "2026-08-30",
      "tags": [
        "003-编程语言"
      ]
    },
    {
      "id": "知识沉淀/编程语言/Python语言/日常探索/Python 语言核心特性调研",
      "title": "Python 语言核心特性调研",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 一句话总结 Python is an easy to learn, powerful programming language. It has efficient high level data structures and a simp",
      "permalink": "/knowledge-base/知识沉淀/编程语言/Python语言/日常探索/Python 语言核心特性调研",
      "date": "2026-08-30",
      "tags": [
        "003-编程语言"
      ]
    },
    {
      "id": "知识沉淀/浏览器验证与AI逆向/多模态AI通用验证码求解服务",
      "title": "用AI从零实现通用验证码求解服务:OhMyCaptcha原理剖析",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 当\"看懂图片\"这件事从传统 CV 的模板匹配/图像处理, 变成\"直接问多模态大模型\", 验证码求解的架构会简化多少? 代价又是什么? 0x00 背景 本笔记沉淀 nax 的博客 文章《用 AI 从零实现通用验证码求解服务：OhMyCaptcha 原",
      "permalink": "/knowledge-base/知识沉淀/浏览器验证与AI逆向/多模态AI通用验证码求解服务",
      "date": "2026-08-26",
      "tags": [
        "AI验证码求解",
        "AI逆向",
        "多模态大模型",
        "浏览器自动化",
        "异步任务"
      ]
    },
    {
      "id": "知识沉淀/浏览器验证与AI逆向/真实浏览器扩展的验证机制拆解",
      "title": "Infinitoai与Turnstile:一次浏览器验证机制的技术拆解",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 一个\"会点复选框\"的脚本和一个\"看起来像真人\"的脚本, 差距究竟在哪一层? 是注入时机, 是事件来源, 还是页面状态感知? 0x00 背景 本笔记沉淀 nax 的博客 文章《Infinitoai 与 Turnstile：一次浏览器验证机制的技术拆解",
      "permalink": "/knowledge-base/知识沉淀/浏览器验证与AI逆向/真实浏览器扩展的验证机制拆解",
      "date": "2026-08-26",
      "tags": [
        "浏览器验证机制",
        "AI逆向",
        "Turnstile",
        "Chrome扩展",
        "事件可信度"
      ]
    },
    {
      "id": "知识沉淀/浏览器验证与AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "title": "深入理解Cloudflare过盾原理:无需AI从零实现CFTurnstile绕过",
      "description": "NOTE 当一个系统反复向你证明\"你是机器人\"时, 它到底在看什么? 是屏幕上的图片, 还是你浏览器内核里每一个不自洽的细节? 0x00 背景 Turnstile 与传统验证码有一个根本差异: 它几乎不出视觉题. 没有扭曲字母, 也没有九宫格选图, 只是在后台收集你浏览器的环境信号, 再判断\"这个环境是不是一个真实的人",
      "permalink": "/knowledge-base/知识沉淀/浏览器验证与AI逆向/CF过盾工程-从零实现Turnstile绕过",
      "date": "2026-08-26",
      "tags": [
        "CF过盾",
        "AI逆向",
        "Turnstile",
        "浏览器指纹",
        "TLS指纹"
      ]
    },
    {
      "id": "知识沉淀/浏览器验证与AI逆向/Turnstile防御面分析与误判权衡",
      "title": "CloudflareTurnstile防御分析:浏览器信号检测面与误判权衡",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 如果一个验证组件注定无法 100% 拦截自动化, 那它存在的意义是什么? 是\"绝对正确\", 还是\"把攻击成本抬到不值得\"? 0x00 背景 本笔记沉淀 nax 的博客 文章《Cloudflare Turnstile 防御分析：浏览器信号、检测面与误",
      "permalink": "/knowledge-base/知识沉淀/浏览器验证与AI逆向/Turnstile防御面分析与误判权衡",
      "date": "2026-08-26",
      "tags": [
        "Turnstile防御",
        "AI逆向",
        "检测面建模",
        "风控",
        "Bot Defense"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/Agent要懂的LLM基础知识",
      "title": "Agent要懂的LLM基础知识",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 一句话总结 Agent 的本质是反复调用 LLM 的循环. 循环里的\"玄学问题\"——聊到 20 30 轮突然不守规矩、第 101 次工具调用输出坏 JSON——不是框架 bug, 而是 LLM 的性质. 从 输入 分词 → 上下文 怎么读",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/Agent要懂的LLM基础知识",
      "date": "2026-08-10",
      "tags": [
        "LLM",
        "AI Agent",
        "Tokenization",
        "KV Cache",
        "约束解码"
      ]
    },
    {
      "id": "知识沉淀/LLM与Agent/AI-Agent设计原理与工程实践",
      "title": "AI Agent设计原理与工程实践",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 一句话总结 生产可用的 Agent 不是\"模型很强\", 而是 Agent = LLM + 上下文 + 工具 + 约束 + 验证 + 纠正 : 模型能力差距在收窄, 竞争优势转移到模型之外的 harness 外壳/脚手架 上. 全书 10 ",
      "permalink": "/knowledge-base/知识沉淀/LLM与Agent/AI-Agent设计原理与工程实践",
      "date": "2026-08-10",
      "tags": [
        "AI Agent",
        "Harness",
        "上下文工程",
        "多智能体",
        "工程实践"
      ]
    },
    {
      "id": "知识沉淀/项目学习/从打野到注册机与AI工具链",
      "title": "从打野到注册机：一条真实项目工具链的工程化学习",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 背景 本文沉淀 Discord 论坛帖子《个人常用项目推荐（打野到注册机一条龙，简易教程）》. 帖子发表于 2026 07 01, 作者为 𝑏𝑎𝑖𝑞𝑖_𝑞𝑎𝑞 , 所在服务器为 KYL , 论坛频道为 🌐 各类教程 ch",
      "permalink": "/knowledge-base/知识沉淀/项目学习/从打野到注册机与AI工具链",
      "date": "2026-08-02",
      "tags": [
        "项目学习",
        "AI Agent",
        "逆向工程",
        "Codex",
        "MCP"
      ]
    },
    {
      "id": "知识沉淀/项目学习/Agent平台/Agent平台数据面灵活解耦",
      "title": "Agent平台数据面灵活解耦",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 背景 Agent 平台通常由控制面和数据面组成. 控制面面向用户, 管理 workspace 的元数据与配置; 数据面承载 Agent 的实际运行环境, 包括文件系统、命令执行和工具调用. 随着 workspace 数量增加、运行环境分化",
      "permalink": "/knowledge-base/知识沉淀/项目学习/Agent平台/Agent平台数据面灵活解耦",
      "date": "2026-07-15",
      "tags": [
        "Agent平台",
        "平台架构",
        "数据面",
        "基础设施"
      ]
    },
    {
      "id": "知识沉淀/商品选购/日常探索/电脑包选购指标",
      "title": "电脑包选购指标",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 这篇笔记来自一段电脑包选购视频的转写整理, 已按「不讨论具体品牌/型号, 只沉淀可复用指标」处理. 0x00 背景 电脑包很容易被商品标题误导: 「大容量」「商务」「旅行」「多功能」「轻便」这些词看起来都对, 但实际到手后可能容量虚、电脑塞不下、背",
      "permalink": "/knowledge-base/知识沉淀/商品选购/日常探索/电脑包选购指标",
      "date": "2026-07-05",
      "tags": [
        "商品选购",
        "电脑包",
        "选购指标",
        "通勤"
      ]
    },
    {
      "id": "知识沉淀/项目学习/ai上下文积累/RTK项目使用说明与Codex本地心得",
      "title": "RTK项目使用说明与Codex本地心得",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 背景 本文沉淀的是 rtk ai/rtk 项目, 即 RTK / Rust Token Killer . 它不是 Redux Toolkit, 也不是别的同名 Rust Type Kit. 这个项目的核心定位是: 在 AI 编程助手执行 ",
      "permalink": "/knowledge-base/知识沉淀/项目学习/ai上下文积累/RTK项目使用说明与Codex本地心得",
      "date": "2026-07-05",
      "tags": [
        "AI工具",
        "RTK",
        "Codex",
        "CLI"
      ]
    },
    {
      "id": "知识沉淀/项目学习/Multica/Multica-agent协作与上下文机制",
      "title": "Multica agent协作与上下文机制",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 这是一篇来自 Multica issue 讨论的阶段性沉淀, 不是 Multica 官方文档. 结论以当前 workspace 运行时注入信息、 multica CLI 读到的 issue/comment 内容和 agent 实际约束为依据. 0x",
      "permalink": "/knowledge-base/知识沉淀/项目学习/Multica/Multica-agent协作与上下文机制",
      "date": "2026-07-05",
      "tags": [
        "Multica",
        "AI Agent",
        "工程协作"
      ]
    },
    {
      "id": "知识沉淀/项目学习/Multica/Multica智能体模板与小队编排skills调研",
      "title": "Multica智能体模板与小队编排skills调研",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 背景 这次调研的直接目标是: 为 Multica 工作区设计一组可复用的 skill, 用来创建智能体、选择和绑定能力、组建小队、编排 issue/stage/autopilot, 并让这些能力真正做到可定制、可快速集成、持续可靠可维护.",
      "permalink": "/knowledge-base/知识沉淀/项目学习/Multica/Multica智能体模板与小队编排skills调研",
      "date": "2026-07-05",
      "tags": [
        "Multica",
        "AI Agent",
        "Skill",
        "工程协作"
      ]
    },
    {
      "id": "知识沉淀/编程语言/Python语言/日常探索/Python爬虫库选型调研",
      "title": "Python爬虫库选型调研",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 当准备写一个 Python 爬虫时, 真正需要先回答的问题不是「哪个库最强」, 而是: 目标页面是否静态? 是否需要登录和浏览器交互? 采集规模是否需要调度、重试和持久化? 最终要的是结构化字段, 还是网页正文? 0x00 背景 Python 爬虫",
      "permalink": "/knowledge-base/知识沉淀/编程语言/Python语言/日常探索/Python爬虫库选型调研",
      "date": "2026-07-04",
      "tags": [
        "Python",
        "爬虫",
        "技术选型"
      ]
    },
    {
      "id": "知识沉淀/现代C++/CppCon/现代C++编译期多态审视",
      "title": "现代C++编译期多态审视",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. 0x00 这篇视频真正要回答什么? 视频讨论的不是一句粗暴的「以后别写 virtual 」, 而是一个更有工程价值的问题: 当程序的类型集合、接口约束和调度路径能够在编译期表达时, 是否还需要把多态性推迟到运行期? 来源信息: 视频: C++虚函数",
      "permalink": "/knowledge-base/知识沉淀/现代C++/CppCon/现代C++编译期多态审视",
      "date": "2026-07-04",
      "tags": [
        "现代C++",
        "C++20",
        "编译期多态",
        "接口设计"
      ]
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain",
      "title": "obsidian-second-brain 中文译注",
      "description": "来源项目: ref/obsidian second brain 来源版本: bf63932 译注目的: 为后续评估 HXLoLi 可以学习哪些知识库/AI 工作流设计做准备。 TIP 这里不是覆盖原项目的“本地化发行版”，而是给 HXLoLi 知识库使用的中文译注。译注保留命令名、路径、frontmatter 字段、脚",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain",
      "date": "2026-07-04",
      "tags": [
        "项目学习",
        "知识库",
        "Skill",
        "增量沉淀"
      ]
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/ai-first-rules",
      "title": "AI-first 笔记规则",
      "description": "对应原文: ref/obsidian second brain/references/ai first rules.md 总原则 vault 是为未来的 Claude 读取和推理而设计，不是优先给人类逐页阅读。用户很少直接打开笔记，而是调用 Claude 在多年积累的知识中检索、综合和连接线索。因此，所有会写入 vau",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/ai-first-rules",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/claude-md-template",
      "title": "_CLAUDE.md 模板",
      "description": "对应原文: ref/obsidian second brain/references/claude md template.md 概念 _CLAUDE.md 是一个放在 vault 根目录的文件。它是 Claude 在 vault 中工作前第一个要读的东西。它给所有 Claude surface 提供同一份操作上下文，",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/claude-md-template",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/commands-index",
      "title": "命令索引",
      "description": "对应原文: ref/obsidian second brain/commands/ .md TIP 命令名不翻译， category 和 triggers_en 保留原样。中文说明是语义译注，便于后续迁移到 HXLoLi 的 AI 工作流。 分类总览 分类 含义 命令数 : vault 日常写入、捕获、查找、任务板、项",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/commands-index",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/ecosystem",
      "title": "生态边界",
      "description": "对应原文: ref/obsidian second brain/ECOSYSTEM.md 核心观点 obsidian second brain 是 core。特定领域 fork 扩展这个模式。 这个页面列出已知 fork: 它们继承 vault rewrite architecture，包括 AI first rule",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/ecosystem",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/fork-insights",
      "title": "Fork 洞察",
      "description": "对应原文: ref/obsidian second brain/FORK_INSIGHTS.md 文档性质 这是 roadmap 文档，不是规范。它分析了 166 个 fork 实际构建了什么，并把可回流上游的内容整理成 50 个具体 additions。优先级标记: P0 : 最高 ROI 的快速收益。 P1 : 很",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/fork-insights",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/hx-loli-adoption-plan",
      "title": "HXLoLi 采纳方案",
      "description": "本文不是翻译，而是把 obsidian second brain 的机制映射到 HXLoLi 当前项目结构中。 当前项目已经有的好基础 独立 AI 知识库 docusaurus.config.ts 里已经把 ai docs/ 配成第二个 @docusaurus/plugin content docs 实例，路由是 /k",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/hx-loli-adoption-plan",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/hx-loli-borrow-list",
      "title": "HXLoLi 可借鉴点",
      "description": "本页基于 ref/obsidian second brain 的中文译注，以及对 HXLoLi 当前结构的快速阅读。它不是最终改造方案，而是下一步可以落地的学习清单。 当前 HXLoLi 已具备的基础 HXLoLi 已经不是单纯博客，项目里有这些可承接点: blog/ : 时间序列文章，适合作为公开输出。 docs/ ",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/hx-loli-borrow-list",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/readme-public",
      "title": "README 公开说明",
      "description": "对应原文: ref/obsidian second brain/README.md 对外定位 obsidian second brain 的对外标语可以译为: 一个代码库，六个 CLI，同一个大脑。 它把自己描述为 Karpathy 的 LLM Wiki 模式的演进: 每个来源会更新已有页面，而不是只追加新页面。 矛盾",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/readme-public",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/skill-manual",
      "title": "Skill 操作手册",
      "description": "对应原文: ref/obsidian second brain/SKILL.md Skill 描述译文 obsidian second brain 用来把任意 Obsidian vault 当作一个活的、会自我重写的第二大脑来操作。它是 Karpathy 的 LLM Wiki 模式的演进版: 新来源会重写已有页面，矛盾",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/skill-manual",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/vault-schema",
      "title": "Vault 结构规范",
      "description": "对应原文: ref/obsidian second brain/references/vault schema.md 默认结构: Wiki style / LLM first 这个结构适用于 Claude 承担大部分或全部写作的 vault。主要读者是 LLM，不是人类。Obsidian 是存储引擎，Claude 是交",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/vault-schema",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/obsidian-second-brain/write-rules",
      "title": "写入规则",
      "description": "对应原文: ref/obsidian second brain/references/write rules.md 前置规则 写任何 Obsidian vault 笔记前，都要先读 references/ai first rules.md 。每条 Claude 写入的笔记都必须遵守 AI first 规则: 前言、丰富",
      "permalink": "/knowledge-base/知识沉淀/项目学习/obsidian-second-brain/write-rules",
      "date": "2026-07-04",
      "tags": []
    },
    {
      "id": "知识沉淀/项目学习/react-bits-classified-study",
      "title": "react-bits 分门别类学习",
      "description": "NOTE 本文由 AI 辅助沉淀, 需要用户 review 后再提交. PPT ppt 0x00 背景 react bits 是一个面向 React 的动效组件源码库, 不是传统意义上 npm install 后直接 import 的运行时组件库. 它的核心价值是把一批视觉表达强、可复制、可按技术栈选择的组件组织成注册",
      "permalink": "/knowledge-base/知识沉淀/项目学习/react-bits-classified-study",
      "date": "2026-07-04",
      "tags": [
        "项目学习",
        "react",
        "前端动画",
        "组件库"
      ]
    },
    {
      "id": "关于",
      "title": "关于",
      "description": "TIP 这里是 HXLoLi 的 AI 沉淀知识库. 当作者懒得写笔记的时候. 则会在此处沉淀. 以防止污染笔记. 此处的笔记应该是使用 skill 按照一定规范和工作流生成. 需要用户 review 修改后再提交. 目标: 减少编写笔记的时间 非期望: 使用ai瞎jb产出",
      "permalink": "/knowledge-base/关于",
      "date": "2026-06-04",
      "tags": []
    },
    {
      "id": "知识沉淀/现代C++/日常探索/HXLibs编写串行协程调度器",
      "title": "HXLibs 协程串行调度器探索",
      "description": "记录 SerialExecutor 三轮迭代的探索过程与踩坑经验。当前版本仍非最终方案, 调度策略尚有优化空间。 相关提交: 50c931c — feat 实现了串行调度器 生命周期敏感 ac74126 — fix 修复 constexpr 编译报错 测试用例 0x00 调度点: 核心思想 在 C++20 无栈协程中实",
      "permalink": "/knowledge-base/知识沉淀/现代C++/日常探索/HXLibs编写串行协程调度器",
      "date": "2026-06-04",
      "tags": [
        "C++",
        "协程",
        "HXLibs"
      ]
    }
  ],
  "generatedAt": "2026-09-13T05:33:01.566Z"
};
