// Auto-generated by docs-rss-plugin — do not edit manually.
export interface LatestDoc {
  title: string;
  to: string;
  date: string;
  category: string;
  description: string;
}

export const latestDocs: LatestDoc[] = [
  {
    "title": "剖析 std::ranges / std::views 库的胖次",
    "to": "/docs/002-程序语言/001-C++/003-现代C++/004-现代C++元模版/004-ranges库",
    "date": "2026-05-10",
    "category": "程序语言",
    "description": ""
  },
  {
    "title": "HX::net 简介",
    "to": "/docs/008-开源项目/001-HXLibs/002-HX-net简介",
    "date": "2026-05-10",
    "category": "开源项目",
    "description": "HX net 为 网络库, 使用 Http1.1 协议; 相关头文件存放于 HXLibs/net 。 一、服务端 1.1 快速示例 一个简单的hello world cpp include <HXLi"
  },
  {
    "title": "分布式系统大厂面试高频知识点图解",
    "to": "/docs/010-面试/分布式系统面试知识点图解",
    "date": "2026-03-06",
    "category": "面试",
    "description": "一、分布式知识体系总览 mermaid mindmap root 分布式系统 理论基础 CAP定理 BASE理论 一致性模型 分布式协调 分布式锁 分布式ID 分布式事务 服务治理 服务注册发现 负载"
  },
  {
    "title": "后端开发大厂面试高频知识点图解（现代C++）",
    "to": "/docs/010-面试/后端开发面试知识点图解",
    "date": "2026-03-06",
    "category": "面试",
    "description": "一、后端知识体系总览 mermaid mindmap root 后端开发 语言基础 现代C++ C++11/14/17/20/23 内存管理 RAII 智能指针 并发编程 模板与泛型编程 Web框架 "
  },
  {
    "title": "操作系统大厂面试高频知识点图解",
    "to": "/docs/010-面试/操作系统面试知识点图解",
    "date": "2026-03-06",
    "category": "面试",
    "description": "一、操作系统整体架构 mermaid mindmap root 操作系统 进程管理 进程与线程 进程调度 进程同步与互斥 死锁 内存管理 虚拟内存 页面置换算法 内存分配 文件系统 文件组织 磁盘调度"
  }
];
