name: "同步番剧数据"
on:
  workflow_call:
    inputs:
      update_type:
        type: string
    outputs:
      changed:
        description: "是否有数据更新"
        value: ${{ jobs.sync.outputs.changed }}

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 安装 uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: 初始化 uv
        run: |
          source $HOME/.cargo/env
          uv sync
        working-directory: ./py

      - name: 是否为全量更新
        run: |
          DO_FULL=false
          if [ "${{ inputs.update_type }}" = "full" ]; then
            DO_FULL=true
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            WEEKDAY=$(TZ=Asia/Shanghai date +%u)
            HOUR=$(TZ=Asia/Shanghai date +%H)
            if [ "$WEEKDAY" -eq 1 ] && [ "$HOUR" -ge 0 ] && [ "$HOUR" -le 3 ]; then
              DO_FULL=true
            fi
          fi
          if [ "$DO_FULL" = "true" ]; then
            rm -f *.json
          fi
        working-directory: ./py/anime/data

      - name: 开始爬取
        run: |
          source $HOME/.cargo/env
          uv run Api.py --username="heng_xin" --token=${{ secrets.BGM_ACCESS_TOKEN }}
        working-directory: ./py/anime
        env:
          PYTHONUNBUFFERED: "1"

      - name: 小萝莉去提交
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[LoLi-Bot]: アニメデータを更新しましたにゃ'
          commit_user_name: 'Heng_Xin[LoLi-Bot]'
          commit_user_email: '282000500@qq.com'